# Code generated by generator.py. DO NOT EDIT.
# Source: flink/minispec.yaml
---
openapi: 3.0.0
info:
  title: Flink Compute Pool Management API
  description: This is the Flink Compute Pool management API.
  version: 0.0.1
  x-api-id: 6dfe8977-3286-4727-ac78-883e0fcba8c0
  x-api-group: fcpm/v2
  x-audience: external-public
  x-tag-group: Compute Pool Mgmt for Flink (%s)
servers:
  - url: https://api.confluent.cloud
    description: Confluent Cloud production
paths:
  /fcpm/v2/compute-pools:
    x-lifecycle-stage: General Availability
    x-self-access: true
    get:
      x-lifecycle-stage: General Availability
      x-self-access: true
      operationId: listFcpmV2ComputePools
      summary: List of Compute Pools
      description: |-
        [![General Availability](https://img.shields.io/badge/Lifecycle%20Stage-General%20Availability-%2345c6e8)](#section/Versioning/API-Lifecycle-Policy)

        Retrieve a sorted, filtered, paginated list of all compute pools.
      parameters:
        - name: spec.region
          in: query
          required: false
          schema:
            $ref: '#/components/schemas/SearchFilter'
          example: us-west-1
          description: Filter the results by exact match for spec.region.
        - name: environment
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/SearchFilter'
          example: env-00000
          description: Filter the results by exact match for environment.
        - name: spec.network
          in: query
          required: false
          schema:
            $ref: '#/components/schemas/SearchFilter'
          example: n-00000
          description: Filter the results by exact match for spec.network.
        - name: page_size
          in: query
          required: false
          schema:
            type: integer
            default: 10
            maximum: 100
            x-max-page-items: 500
          description: A pagination size for collection requests.
        - name: page_token
          in: query
          required: false
          schema:
            type: string
            maxLength: 255
          description: An opaque pagination token for collection requests.
      tags:
        - Compute Pools (fcpm/v2)
      security:
        - cloud-api-key: []
        - confluent-sts-access-token: []
      responses:
        '200':
          description: Compute Pool.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/fcpm.v2.ComputePoolList'
                  - type: object
                    properties:
                      data:
                        type: array
                        items:
                          properties:
                            spec:
                              type: object
                              properties:
                                environment:
                                  example:
                                    id: env-00000
                                    related: https://api.confluent.cloud/org/v2/environments/env-00000
                                    resource_name: https://api.confluent.cloud/organization=9bb441c4-edef-46ac-8a41-c49e44a3fd9a/environment=env-00000
                                network:
                                  example:
                                    id: n-00000
                                    related: https://api.confluent.cloud/networking/v1/networks/n-00000
                                    resource_name: https://api.confluent.cloud/organization=9bb441c4-edef-46ac-8a41-c49e44a3fd9a/environment=env-abc123/network=n-00000
          headers:
            X-Request-Id:
              schema:
                type: string
              description: The unique identifier for the API request.
            X-RateLimit-Limit:
              schema:
                type: integer
              description: The maximum number of requests you're permitted to make per time period.
            X-RateLimit-Remaining:
              schema:
                type: integer
              description: The number of requests remaining in the current rate limit window.
            X-RateLimit-Reset:
              schema:
                type: integer
              description: "The relative time in seconds until the current rate-limit window resets.  \n  \n**Important:**\
                \ This differs from Github and Twitter's same-named header which uses UTC epoch seconds. We use relative time\
                \ to avoid client/server time synchronization issues."
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/UnauthenticatedError'
        '403':
          $ref: '#/components/responses/UnauthorizedError'
        '429':
          $ref: '#/components/responses/RateLimitError'
        '500':
          $ref: '#/components/responses/DefaultSystemError'
    post:
      x-lifecycle-stage: General Availability
      x-self-access: true
      operationId: createFcpmV2ComputePool
      summary: Create a Compute Pool
      description: |-
        [![General Availability](https://img.shields.io/badge/Lifecycle%20Stage-General%20Availability-%2345c6e8)](#section/Versioning/API-Lifecycle-Policy)

        Make a request to create a compute pool.
      tags:
        - Compute Pools (fcpm/v2)
      security:
        - cloud-api-key: []
        - confluent-sts-access-token: []
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/fcpm.v2.ComputePool'
                - type: object
                  required:
                    - spec
                  properties:
                    spec:
                      type: object
                      required:
                        - display_name
                        - cloud
                        - region
                        - max_cfu
                        - environment
                - type: object
                  properties:
                    spec:
                      type: object
                      properties:
                        environment:
                          example:
                            id: env-00000
                        network:
                          example:
                            id: n-00000
      responses:
        '202':
          description: A Compute Pool is being created.
          headers:
            X-Request-Id:
              schema:
                type: string
              description: The unique identifier for the API request.
            X-RateLimit-Limit:
              schema:
                type: integer
              description: The maximum number of requests you're permitted to make per time period.
            X-RateLimit-Remaining:
              schema:
                type: integer
              description: The number of requests remaining in the current rate limit window.
            X-RateLimit-Reset:
              schema:
                type: integer
              description: "The relative time in seconds until the current rate-limit window resets.  \n  \n**Important:**\
                \ This differs from Github and Twitter's same-named header which uses UTC epoch seconds. We use relative time\
                \ to avoid client/server time synchronization issues."
            Location:
              schema:
                type: string
                format: uri
                example: https://api.confluent.cloud/fcpm/v2/compute-pools/{id}
              description: ComputePool resource uri
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/fcpm.v2.ComputePool'
                  - type: object
                    required:
                      - spec
                      - status
                    properties:
                      spec:
                        type: object
                        required:
                          - display_name
                          - cloud
                          - region
                          - max_cfu
                          - environment
                  - type: object
                    properties:
                      spec:
                        type: object
                        properties:
                          environment:
                            example:
                              id: env-00000
                              related: https://api.confluent.cloud/org/v2/environments/env-00000
                              resource_name: https://api.confluent.cloud/organization=9bb441c4-edef-46ac-8a41-c49e44a3fd9a/environment=env-00000
                          network:
                            example:
                              id: n-00000
                              related: https://api.confluent.cloud/networking/v1/networks/n-00000
                              resource_name: https://api.confluent.cloud/organization=9bb441c4-edef-46ac-8a41-c49e44a3fd9a/environment=env-abc123/network=n-00000
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/UnauthenticatedError'
        '403':
          $ref: '#/components/responses/UnauthorizedError'
        '409':
          $ref: '#/components/responses/ConflictError'
        '422':
          $ref: '#/components/responses/ValidationError'
        '429':
          $ref: '#/components/responses/RateLimitError'
        '500':
          $ref: '#/components/responses/DefaultSystemError'
  /fcpm/v2/compute-pools/{id}:
    x-lifecycle-stage: General Availability
    x-self-access: true
    get:
      x-lifecycle-stage: General Availability
      x-self-access: true
      operationId: getFcpmV2ComputePool
      summary: Read a Compute Pool
      description: |-
        [![General Availability](https://img.shields.io/badge/Lifecycle%20Stage-General%20Availability-%2345c6e8)](#section/Versioning/API-Lifecycle-Policy)

        Make a request to read a compute pool.
      parameters:
        - name: environment
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/SearchFilter'
          example: env-00000
          description: Scope the operation to the given environment.
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: The unique identifier for the compute pool.
      tags:
        - Compute Pools (fcpm/v2)
      security:
        - cloud-api-key: []
        - confluent-sts-access-token: []
      responses:
        '200':
          description: Compute Pool.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/fcpm.v2.ComputePool'
                  - type: object
                    required:
                      - api_version
                      - kind
                      - id
                      - spec
                      - status
                    properties:
                      spec:
                        type: object
                        required:
                          - display_name
                          - cloud
                          - region
                          - max_cfu
                          - environment
                  - type: object
                    properties:
                      spec:
                        type: object
                        properties:
                          environment:
                            example:
                              id: env-00000
                              related: https://api.confluent.cloud/org/v2/environments/env-00000
                              resource_name: https://api.confluent.cloud/organization=9bb441c4-edef-46ac-8a41-c49e44a3fd9a/environment=env-00000
                          network:
                            example:
                              id: n-00000
                              related: https://api.confluent.cloud/networking/v1/networks/n-00000
                              resource_name: https://api.confluent.cloud/organization=9bb441c4-edef-46ac-8a41-c49e44a3fd9a/environment=env-abc123/network=n-00000
          headers:
            X-Request-Id:
              schema:
                type: string
              description: The unique identifier for the API request.
            X-RateLimit-Limit:
              schema:
                type: integer
              description: The maximum number of requests you're permitted to make per time period.
            X-RateLimit-Remaining:
              schema:
                type: integer
              description: The number of requests remaining in the current rate limit window.
            X-RateLimit-Reset:
              schema:
                type: integer
              description: "The relative time in seconds until the current rate-limit window resets.  \n  \n**Important:**\
                \ This differs from Github and Twitter's same-named header which uses UTC epoch seconds. We use relative time\
                \ to avoid client/server time synchronization issues."
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/UnauthenticatedError'
        '403':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '429':
          $ref: '#/components/responses/RateLimitError'
        '500':
          $ref: '#/components/responses/DefaultSystemError'
    patch:
      x-lifecycle-stage: General Availability
      x-self-access: true
      operationId: updateFcpmV2ComputePool
      summary: Update a Compute Pool
      description: |-
        [![General Availability](https://img.shields.io/badge/Lifecycle%20Stage-General%20Availability-%2345c6e8)](#section/Versioning/API-Lifecycle-Policy)

        Make a request to update a compute pool.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: The unique identifier for the compute pool.
      tags:
        - Compute Pools (fcpm/v2)
      security:
        - cloud-api-key: []
        - confluent-sts-access-token: []
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/fcpm.v2.ComputePool'
                - type: object
                  required:
                    - spec
                  properties:
                    spec:
                      type: object
                      required:
                        - environment
                      properties:
                        environment:
                          example:
                            id: env-00000
      responses:
        '200':
          description: Compute Pool.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/fcpm.v2.ComputePool'
                  - type: object
                    required:
                      - api_version
                      - kind
                      - id
                      - spec
                      - status
                    properties:
                      spec:
                        type: object
                        required:
                          - display_name
                          - cloud
                          - region
                          - max_cfu
                          - environment
                  - type: object
                    properties:
                      spec:
                        type: object
                        properties:
                          environment:
                            example:
                              id: env-00000
                              related: https://api.confluent.cloud/org/v2/environments/env-00000
                              resource_name: https://api.confluent.cloud/organization=9bb441c4-edef-46ac-8a41-c49e44a3fd9a/environment=env-00000
                          network:
                            example:
                              id: n-00000
                              related: https://api.confluent.cloud/networking/v1/networks/n-00000
                              resource_name: https://api.confluent.cloud/organization=9bb441c4-edef-46ac-8a41-c49e44a3fd9a/environment=env-abc123/network=n-00000
          headers:
            X-Request-Id:
              schema:
                type: string
              description: The unique identifier for the API request.
            X-RateLimit-Limit:
              schema:
                type: integer
              description: The maximum number of requests you're permitted to make per time period.
            X-RateLimit-Remaining:
              schema:
                type: integer
              description: The number of requests remaining in the current rate limit window.
            X-RateLimit-Reset:
              schema:
                type: integer
              description: "The relative time in seconds until the current rate-limit window resets.  \n  \n**Important:**\
                \ This differs from Github and Twitter's same-named header which uses UTC epoch seconds. We use relative time\
                \ to avoid client/server time synchronization issues."
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/UnauthenticatedError'
        '403':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '409':
          $ref: '#/components/responses/ConflictError'
        '422':
          $ref: '#/components/responses/ValidationError'
        '429':
          $ref: '#/components/responses/RateLimitError'
        '500':
          $ref: '#/components/responses/DefaultSystemError'
    delete:
      x-lifecycle-stage: General Availability
      x-self-access: true
      operationId: deleteFcpmV2ComputePool
      summary: Delete a Compute Pool
      description: |-
        [![General Availability](https://img.shields.io/badge/Lifecycle%20Stage-General%20Availability-%2345c6e8)](#section/Versioning/API-Lifecycle-Policy)

        Make a request to delete a compute pool.
      parameters:
        - name: environment
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/SearchFilter'
          example: env-00000
          description: Scope the operation to the given environment.
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: The unique identifier for the compute pool.
      tags:
        - Compute Pools (fcpm/v2)
      security:
        - cloud-api-key: []
        - confluent-sts-access-token: []
      responses:
        '204':
          description: A Compute Pool is being deleted.
          headers:
            X-Request-Id:
              schema:
                type: string
              description: The unique identifier for the API request.
            X-RateLimit-Limit:
              schema:
                type: integer
              description: The maximum number of requests you're permitted to make per time period.
            X-RateLimit-Remaining:
              schema:
                type: integer
              description: The number of requests remaining in the current rate limit window.
            X-RateLimit-Reset:
              schema:
                type: integer
              description: "The relative time in seconds until the current rate-limit window resets.  \n  \n**Important:**\
                \ This differs from Github and Twitter's same-named header which uses UTC epoch seconds. We use relative time\
                \ to avoid client/server time synchronization issues."
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/UnauthenticatedError'
        '403':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '429':
          $ref: '#/components/responses/RateLimitError'
        '500':
          $ref: '#/components/responses/DefaultSystemError'
  /fcpm/v2/regions:
    x-lifecycle-stage: General Availability
    x-self-access: true
    get:
      x-lifecycle-stage: General Availability
      x-self-access: true
      operationId: listFcpmV2Regions
      summary: List of Regions
      description: |-
        [![General Availability](https://img.shields.io/badge/Lifecycle%20Stage-General%20Availability-%2345c6e8)](#section/Versioning/API-Lifecycle-Policy)

        Retrieve a sorted, filtered, paginated list of all regions.
      parameters:
        - name: cloud
          in: query
          required: false
          schema:
            $ref: '#/components/schemas/SearchFilter'
          example: AWS
          description: Filter the results by exact match for cloud.
        - name: region_name
          in: query
          required: false
          schema:
            $ref: '#/components/schemas/SearchFilter'
          example: us-east-2
          description: Filter the results by exact match for region_name.
        - name: page_size
          in: query
          required: false
          schema:
            type: integer
            default: 10
            maximum: 100
            x-max-page-items: 500
          description: A pagination size for collection requests.
        - name: page_token
          in: query
          required: false
          schema:
            type: string
            maxLength: 255
          description: An opaque pagination token for collection requests.
      tags:
        - Regions (fcpm/v2)
      security:
        - cloud-api-key: []
        - confluent-sts-access-token: []
      responses:
        '200':
          description: Region.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/fcpm.v2.RegionList'
          headers:
            X-Request-Id:
              schema:
                type: string
              description: The unique identifier for the API request.
            X-RateLimit-Limit:
              schema:
                type: integer
              description: The maximum number of requests you're permitted to make per time period.
            X-RateLimit-Remaining:
              schema:
                type: integer
              description: The number of requests remaining in the current rate limit window.
            X-RateLimit-Reset:
              schema:
                type: integer
              description: "The relative time in seconds until the current rate-limit window resets.  \n  \n**Important:**\
                \ This differs from Github and Twitter's same-named header which uses UTC epoch seconds. We use relative time\
                \ to avoid client/server time synchronization issues."
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/UnauthenticatedError'
        '403':
          $ref: '#/components/responses/UnauthorizedError'
        '429':
          $ref: '#/components/responses/RateLimitError'
        '500':
          $ref: '#/components/responses/DefaultSystemError'
components:
  schemas:
    fcpm.v2.ComputePool:
      type: object
      description: |-
        A Compute Pool represents a set of compute resources that is used to run your Queries.
        The resources (CPUs, memory,…) provided by a Compute Pool are shared between all Queries that use it.


        ## The Compute Pools Model
        <SchemaDefinition schemaRef="#/components/schemas/fcpm.v2.ComputePool" />
      properties:
        api_version:
          type: string
          enum:
            - fcpm/v2
          description: APIVersion defines the schema version of this representation of a resource.
          readOnly: true
        kind:
          type: string
          description: Kind defines the object this REST resource represents.
          readOnly: true
          enum:
            - ComputePool
        id:
          description: ID is the "natural identifier" for an object within its scope/namespace; it is normally unique across
            time but not space. That is, you can assume that the ID will not be reclaimed and reused after an object is deleted
            ("time"); however, it may collide with IDs for other object `kinds` or objects of the same `kind` within a different
            scope/namespace ("space").
          type: string
          maxLength: 255
          readOnly: true
          example: dlz-f3a90de
        metadata:
          allOf:
            - $ref: '#/components/schemas/ObjectMeta'
            - properties:
                self:
                  example: https://api.confluent.cloud/fcpm/v2/compute-pools/lfcp-12345
                resource_name:
                  example: crn://confluent.cloud/organization=9bb441c4-edef-46ac-8a41-c49e44a3fd9a/environment=env-abc123/flink-region=aws.us-east-2/compute-pool=lfcp-12345
        spec:
          $ref: '#/components/schemas/fcpm.v2.ComputePoolSpec'
        status:
          $ref: '#/components/schemas/fcpm.v2.ComputePoolStatus'
    fcpm.v2.ComputePoolStatus:
      type: object
      required:
        - phase
        - current_cfu
      description: The status of the Compute Pool
      properties:
        phase:
          type: string
          x-extensible-enum: [PROVISIONING, PROVISIONED, FAILED, DEPROVISIONING]
          description: Status of the Flink compute pool.
          example: PROVISIONING
          readOnly: true
        current_cfu:
          type: integer
          format: int32
          example: 4
          description: The number of Confluent Flink Units (CFUs) currently allocated to this Flink compute pool.
          readOnly: true
      readOnly: true
    fcpm.v2.Region:
      type: object
      description: |-
        `Region` objects represent cloud provider regions available when placing Flink compute pools.
        The API allows you to list Flink regions.


        ## The Regions Model
        <SchemaDefinition schemaRef="#/components/schemas/fcpm.v2.Region" />
      properties:
        api_version:
          type: string
          enum:
            - fcpm/v2
          description: APIVersion defines the schema version of this representation of a resource.
          readOnly: true
        kind:
          type: string
          description: Kind defines the object this REST resource represents.
          readOnly: true
          enum:
            - Region
        id:
          description: ID is the "natural identifier" for an object within its scope/namespace; it is normally unique across
            time but not space. That is, you can assume that the ID will not be reclaimed and reused after an object is deleted
            ("time"); however, it may collide with IDs for other object `kinds` or objects of the same `kind` within a different
            scope/namespace ("space").
          type: string
          maxLength: 255
          readOnly: true
          example: dlz-f3a90de
        metadata:
          allOf:
            - $ref: '#/components/schemas/ObjectMeta'
            - properties:
                self:
                  example: https://api.confluent.cloud/fcpm/v2/regions/r-12345
                resource_name:
                  example: crn://confluent.cloud/organization=9bb441c4-edef-46ac-8a41-c49e44a3fd9a/region=r-12345
        display_name:
          type: string
          description: The display name.
          example: Ohio (us-east-2)
          x-immutable: true
          readOnly: true
        cloud:
          type: string
          description: The cloud service provider that hosts the region.
          x-extensible-enum: [AWS, GCP, AZURE]
          example: AWS
          x-immutable: true
          readOnly: true
        region_name:
          type: string
          description: The region name.
          example: us-east-2
          x-immutable: true
          readOnly: true
        http_endpoint:
          type: string
          description: The regional API endpoint for Flink compute pools.
          format: uri
          x-immutable: true
          readOnly: true
        private_http_endpoint:
          type: string
          description: The private regional API endpoint for Flink compute pools.
          format: uri
          x-immutable: true
          readOnly: true
    SearchFilter:
      description: Filter a collection by a string search
      type: string
    fcpm.v2.ComputePoolList:
      type: object
      description: |-
        A Compute Pool represents a set of compute resources that is used to run your Queries.
        The resources (CPUs, memory,…) provided by a Compute Pool are shared between all Queries that use it.


        ## The Compute Pools Model
        <SchemaDefinition schemaRef="#/components/schemas/fcpm.v2.ComputePool" />
      required:
        - api_version
        - kind
        - metadata
        - data
      properties:
        api_version:
          type: string
          enum:
            - fcpm/v2
          description: APIVersion defines the schema version of this representation of a resource.
          readOnly: true
        kind:
          type: string
          description: Kind defines the object this REST resource represents.
          readOnly: true
          enum:
            - ComputePoolList
        metadata:
          allOf:
            - $ref: '#/components/schemas/ListMeta'
            - properties:
                first:
                  example: https://api.confluent.cloud/fcpm/v2/compute-pools
                last:
                  example: https://api.confluent.cloud/fcpm/v2/compute-pools?page_token=bcAOehAY8F16YD84Z1wT
                prev:
                  example: https://api.confluent.cloud/fcpm/v2/compute-pools?page_token=YIXRY97wWYmwzrax4dld
                next:
                  example: https://api.confluent.cloud/fcpm/v2/compute-pools?page_token=UvmDWOB1iwfAIBPj6EYb
        data:
          type: array
          description: A data property that contains an array of resource items. Each entry in the array is a separate resource.
          items:
            allOf:
              - $ref: '#/components/schemas/fcpm.v2.ComputePool'
              - type: object
                required:
                  - id
                  - metadata
                  - spec
                  - status
                properties:
                  spec:
                    type: object
                    required:
                      - display_name
                      - cloud
                      - region
                      - max_cfu
                      - environment
          uniqueItems: true
    fcpm.v2.ComputePoolSpec:
      type: object
      description: The desired state of the Compute Pool
      properties:
        display_name:
          type: string
          example: flink_compute_pool_0
          description: The name of the Flink compute pool.
          pattern: ^(?:[0-9A-Za-z\-])[\w\.-]{0,63}$
          x-immutable: false
        cloud:
          type: string
          description: The cloud service provider that runs the compute pool.
          x-extensible-enum: [AWS, GCP, AZURE]
          example: AWS
          x-immutable: true
        region:
          type: string
          example: us-west-1
          description: Flink compute pools in the region provided will be able to use this identity pool
          x-immutable: true
        max_cfu:
          type: integer
          format: int32
          example: 5
          description: |
            Maximum number of Confluent Flink Units (CFUs) that the Flink compute pool should auto-scale to.
          x-extensible-enum: [5, 10, 20, 30, 40, 50]
          x-immutable: false
        enable_ai:
          type: boolean
          default: false
          description: |
            The flag to enable AI computing using Ray for the Flink compute pool. It's available in the Early Access API
            lifecycle stage only.
          x-immutable: true
        environment:
          allOf:
            - $ref: '#/components/schemas/GlobalObjectReference'
          description: The environment to which this belongs.
        network:
          allOf:
            - $ref: '#/components/schemas/EnvScopedObjectReference'
          description: The network to which this belongs.
          x-immutable: true
      x-enable-id: true
      x-enable-listmeta: true
      x-enable-objectmeta: true
    fcpm.v2.RegionList:
      type: object
      description: |-
        `Region` objects represent cloud provider regions available when placing Flink compute pools.
        The API allows you to list Flink regions.


        ## The Regions Model
        <SchemaDefinition schemaRef="#/components/schemas/fcpm.v2.Region" />
      required:
        - api_version
        - kind
        - metadata
        - data
      properties:
        api_version:
          type: string
          enum:
            - fcpm/v2
          description: APIVersion defines the schema version of this representation of a resource.
          readOnly: true
        kind:
          type: string
          description: Kind defines the object this REST resource represents.
          readOnly: true
          enum:
            - RegionList
        metadata:
          allOf:
            - $ref: '#/components/schemas/ListMeta'
            - properties:
                first:
                  example: https://api.confluent.cloud/fcpm/v2/regions
                last:
                  example: https://api.confluent.cloud/fcpm/v2/regions?page_token=bcAOehAY8F16YD84Z1wT
                prev:
                  example: https://api.confluent.cloud/fcpm/v2/regions?page_token=YIXRY97wWYmwzrax4dld
                next:
                  example: https://api.confluent.cloud/fcpm/v2/regions?page_token=UvmDWOB1iwfAIBPj6EYb
        data:
          type: array
          description: A data property that contains an array of resource items. Each entry in the array is a separate resource.
          items:
            allOf:
              - $ref: '#/components/schemas/fcpm.v2.Region'
              - type: object
                required:
                  - id
                  - metadata
                  - display_name
                  - cloud
                  - region_name
                  - http_endpoint
          uniqueItems: true
    ObjectMeta:
      description: ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create.
      required:
        - self
      properties:
        self:
          description: Self is a Uniform Resource Locator (URL) at which an object can be addressed. This URL encodes the
            service location, API version, and other particulars necessary to locate the resource at a point in time
          type: string
          format: uri
          readOnly: true
          example: https://api.confluent.cloud/v2/kafka-clusters/lkc-f3a90de
        resource_name:
          description: Resource Name is a Uniform Resource Identifier (URI) that is globally unique across space and time.
            It is represented as a Confluent Resource Name
          type: string
          format: uri
          readOnly: true
          example: crn://confluent.cloud/kafka=lkc-f3a90de
        created_at:
          type: string
          format: date-time
          example: '2006-01-02T15:04:05-07:00'
          readOnly: true
          description: The date and time at which this object was created. It is represented in RFC3339 format and is in UTC.
        updated_at:
          type: string
          format: date-time
          example: '2006-01-02T15:04:05-07:00'
          readOnly: true
          description: The date and time at which this object was last updated. It is represented in RFC3339 format and is
            in UTC.
        deleted_at:
          type: string
          format: date-time
          example: '2006-01-02T15:04:05-07:00'
          readOnly: true
          description: The date and time at which this object was (or will be) deleted. It is represented in RFC3339 format
            and is in UTC.
      readOnly: true
    ListMeta:
      type: object
      description: ListMeta describes metadata that resource collections may have
      properties:
        first:
          description: A link to the first page of results. If a response does not contain a first link, then direct navigation
            to the first page is not supported.
          type: string
          format: uri
          nullable: true
          example: https://api.confluent.cloud/v2/resourcekinds
        last:
          description: A link to the last page of results. If a response does not contain a last link, then direct navigation
            to the last page is not supported.
          type: string
          format: uri
          nullable: true
          example: https://api.confluent.cloud/v2/resourcekinds?page_token=bcAOehAY8F16YD84Z1wT
        prev:
          description: A link to the previous page of results. If a response does not contain a prev link, then either there
            is no previous data or backwards traversal through the result set is not supported.
          type: string
          format: uri
          nullable: true
          example: https://api.confluent.cloud/v2/resourcekinds?page_token=YIXRY97wWYmwzrax4dld
        next:
          description: A link to the next page of results. If a response does not contain a next link, then there is no more
            data available.
          type: string
          format: uri
          nullable: true
          example: https://api.confluent.cloud/v2/resourcekinds?page_token=UvmDWOB1iwfAIBPj6EYb
        total_size:
          description: Number of records in the full result set. This response may be paginated and have a smaller number
            of records.
          type: integer
          format: int32
          minimum: 0
          example: 123
    ObjectReference:
      type: object
      description: ObjectReference provides information for you to locate the referred object
      required:
        - id
        - related
        - resource_name
      properties:
        id:
          type: string
          description: ID of the referred resource
          minLength: 1
          maxLength: 255
        environment:
          type: string
          description: Environment of the referred resource, if env-scoped
          minLength: 1
          maxLength: 255
        related:
          type: string
          format: uri
          description: API URL for accessing or modifying the referred object
          minLength: 1
          readOnly: true
        resource_name:
          type: string
          format: uri
          description: CRN reference to the referred resource
          minLength: 1
          readOnly: true
        api_version:
          type: string
          description: API group and version of the referred resource
          minLength: 1
          readOnly: true
        kind:
          type: string
          description: Kind of the referred resource
          minLength: 1
          readOnly: true
    GlobalObjectReference:
      type: object
      description: ObjectReference provides information for you to locate the referred object
      required:
        - id
        - related
        - resource_name
      properties:
        id:
          type: string
          description: ID of the referred resource
          minLength: 1
          maxLength: 255
        related:
          type: string
          format: uri
          description: API URL for accessing or modifying the referred object
          minLength: 1
          readOnly: true
        resource_name:
          type: string
          format: uri
          description: CRN reference to the referred resource
          minLength: 1
          readOnly: true
    EnvScopedObjectReference:
      type: object
      description: ObjectReference provides information for you to locate the referred object
      required:
        - id
        - related
        - resource_name
      properties:
        id:
          type: string
          description: ID of the referred resource
          minLength: 1
          maxLength: 255
        environment:
          type: string
          description: Environment of the referred resource, if env-scoped
          minLength: 1
          maxLength: 255
        related:
          type: string
          format: uri
          description: API URL for accessing or modifying the referred object
          minLength: 1
          readOnly: true
        resource_name:
          type: string
          format: uri
          description: CRN reference to the referred resource
          minLength: 1
          readOnly: true
    Failure:
      type: object
      description: Provides information about problems encountered while performing an operation.
      required:
        - errors
      properties:
        errors:
          description: List of errors which caused this operation to fail
          type: array
          items:
            $ref: '#/components/schemas/Error'
          uniqueItems: true
    Error:
      type: object
      description: Describes a particular error encountered while performing an operation.
      properties:
        id:
          description: A unique identifier for this particular occurrence of the problem.
          type: string
          maxLength: 255
        status:
          description: The HTTP status code applicable to this problem, expressed as a string value.
          type: string
        code:
          description: An application-specific error code, expressed as a string value.
          type: string
        title:
          description: A short, human-readable summary of the problem. It **SHOULD NOT** change from occurrence to occurrence
            of the problem, except for purposes of localization.
          type: string
        detail:
          description: A human-readable explanation specific to this occurrence of the problem.
          type: string
        source:
          type: object
          description: If this error was caused by a particular part of the API request, the source will point to the query
            string parameter or request body property that caused it.
          properties:
            pointer:
              description: A JSON Pointer [RFC6901] to the associated entity in the request document [e.g. "/spec" for a spec
                object, or "/spec/title" for a specific field].
              type: string
            parameter:
              description: A string indicating which query parameter caused the error.
              type: string
  securitySchemes:
    cloud-api-key:
      type: http
      scheme: basic
      description: Authenticate with Cloud API Keys using HTTP Basic Auth. Treat the Cloud API Key ID as the username and
        Cloud API Key Secret as the password.
    confluent-sts-access-token:
      type: oauth2
      description: Authenticate with Confluent API using this credentials (JSON Web Tokens) following OAuth 2.0.
      flows:
        clientCredentials:
          tokenUrl: https://api.confluent.cloud/sts/v1/oauth2/token
          scopes: {}
  responses:
    BadRequestError:
      description: Bad Request
      headers:
        X-Request-Id:
          schema:
            type: string
          description: The unique identifier for the API request.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Failure'
          example:
            errors:
              - id: ed42afdc-f0d5-4c0d-b428-9fc6ed6e279d
                status: '400'
                code: invalid_filter
                title: Invalid Filter
                detail: The 'delorean' resource can't be filtered by 'num_doors'
                source:
                  parameter: num_doors
    UnauthenticatedError:
      x-summary: Unauthorized
      description: The request lacks valid authentication credentials for this resource.
      headers:
        X-Request-Id:
          schema:
            type: string
          description: The unique identifier for the API request.
        WWW-Authenticate:
          schema:
            type: string
          description: The unique identifier for the API request.
          example: Basic error="invalid_key", error_description="The API Key is invalid"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Failure'
          example:
            errors:
              - id: ed42afdc-f0d5-4c0d-b428-9fc6ed6e279d
                status: '401'
                code: user_unauthenticated
                title: Authentication Required
                detail: Valid authentication credentials must be provided
    OverQuotaError:
      x-summary: Over Quota
      description: The request would exceed one or more quotas.
      headers:
        X-Request-Id:
          schema:
            type: string
          description: The unique identifier for the API request.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Failure'
          example:
            errors:
              - id: ed42afdc-f0d5-4c0d-b428-9fc6ed6e279d
                status: '402'
                code: quota_exceeded
                title: Kafka Clusters Per Org Quota Exceeded
                detail: 'The request would exceed the quota: kafka_clusters_per_environment'
    UnauthorizedError:
      x-summary: Forbidden
      description: The access credentials were considered insufficient to grant access
      headers:
        X-Request-Id:
          schema:
            type: string
          description: The unique identifier for the API request.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Failure'
          example:
            errors:
              - id: ed42afdc-f0d5-4c0d-b428-9fc6ed6e279d
                status: '403'
                code: user_unauthorized
                title: User Access Unauthorized
                detail: The user 'mcfly' is not allowed to access the 'delorean' resource without the 'plutonium' role.
    ConflictError:
      x-summary: Conflict
      description: The request is in conflict with the current server state
      headers:
        X-Request-Id:
          schema:
            type: string
          description: The unique identifier for the API request.
        Location:
          schema:
            type: string
            format: uri
            example: https://api.confluent.cloud/{object}/{id}
          description: Resource URI of conflicting resource
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Failure'
          example:
            errors:
              - id: ed42afdc-f0d5-4c0d-b428-9fc6ed6e279d
                status: '409'
                code: resource_already_exists
                title: Resource Already exists
                detail: The entitlement '91e3e86f-fca6-4f14-98f5-a48e64113ce2' already exists.
    NotFoundError:
      description: Not Found
      headers:
        X-Request-Id:
          schema:
            type: string
          description: The unique identifier for the API request.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Failure'
          example:
            errors:
              - id: ed42afdc-f0d5-4c0d-b428-9fc6ed6e279d
                status: '404'
                title: Not Found
    ValidationError:
      description: Validation Failed
      headers:
        X-Request-Id:
          schema:
            type: string
          description: The unique identifier for the API request.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Failure'
          example:
            errors:
              - status: '422'
                code: invalid_configuration
                id: ed42afdc-f0d5-4c0d-b428-9fc6ed6e279d
                title: Validation Failed
                detail: "The property '/cluster/storage_size' of type string did not match the following type: integer"
                source:
                  pointer: /cluster/storage_size
    RateLimitError:
      description: Rate Limit Exceeded
      headers:
        X-Request-Id:
          schema:
            type: string
          description: The unique identifier for the API request.
        X-RateLimit-Limit:
          schema:
            type: integer
          description: The maximum number of requests you're permitted to make per time period.
        X-RateLimit-Remaining:
          schema:
            type: integer
          description: The number of requests remaining in the current rate limit window.
        X-RateLimit-Reset:
          schema:
            type: integer
          description: "The relative time in seconds until the current rate-limit window resets.  \n  \n**Important:** This\
            \ differs from Github and Twitter's same-named header which uses UTC epoch seconds. We use relative time to avoid\
            \ client/server time synchronization issues."
        Retry-After:
          schema:
            type: integer
          description: The number of seconds to wait until the rate limit window resets. Only sent when the rate limit is
            reached.
    DefaultSystemError:
      description: Oops, something went wrong!
      headers:
        X-Request-Id:
          schema:
            type: string
          description: The unique identifier for the API request.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Failure'
          example:
            errors:
              - id: ed42afdc-f0d5-4c0d-b428-9fc6ed6e279d
                status: '500'
                code: out_of_gas
                title: DeLorean Out Of Gas
                detail: The DeLorean has run out of gas, but Doc Brown will fill 'er up for you asap
tags:
  - name: Compute Pools (fcpm/v2)
    description: |-
      [![General Availability](https://img.shields.io/badge/Lifecycle%20Stage-General%20Availability-%2345c6e8)](#section/Versioning/API-Lifecycle-Policy)

      A Compute Pool represents a set of compute resources that is used to run your Queries.
      The resources (CPUs, memory,…) provided by a Compute Pool are shared between all Queries that use it.


      ## The Compute Pools Model
      <SchemaDefinition schemaRef="#/components/schemas/fcpm.v2.ComputePool" />
  - name: Regions (fcpm/v2)
    description: |-
      [![General Availability](https://img.shields.io/badge/Lifecycle%20Stage-General%20Availability-%2345c6e8)](#section/Versioning/API-Lifecycle-Policy)

      `Region` objects represent cloud provider regions available when placing Flink compute pools.
      The API allows you to list Flink regions.


      ## The Regions Model
      <SchemaDefinition schemaRef="#/components/schemas/fcpm.v2.Region" />
