# Code generated by generator.py. DO NOT EDIT.
# Source: flink-artifact/minispec.yaml
---
openapi: 3.0.0
info:
  title: Flink Artifact Management API
  description: This is the Flink Artifact Management API.
  version: 0.0.1
  x-api-id: 6dfe8977-3286-4727-ac78-883e0fcba8c0
  x-api-group: artifact/v1
  x-audience: external-public
  x-tag-group: Artifact API (%s)

servers:
  - url: https://api.confluent.cloud
    description: Confluent Cloud production

paths:
  /artifact/v1/flink-artifacts:
    x-lifecycle-stage: General Availability
    x-self-access: true
    get:
      x-lifecycle-stage: General Availability
      x-self-access: true
      operationId: listArtifactV1FlinkArtifacts
      summary: List of Flink Artifacts
      description: |-
        [![General Availability](https://img.shields.io/badge/Lifecycle%20Stage-General%20Availability-%2345c6e8)](#section/Versioning/API-Lifecycle-Policy)

        Retrieve a sorted, filtered, paginated list of all flink artifacts.
      parameters:
        - name: cloud
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/SearchFilter'
          example: AWS
          description: Filter the results by exact match for cloud.
        - name: region
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/SearchFilter'
          example: us-east-1
          description: Filter the results by exact match for region.
        - name: environment
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/SearchFilter'
          example: env-00000
          description: Filter the results by exact match for environment.
        - name: page_size
          in: query
          required: false
          schema:
            type: integer
            default: 10
            maximum: 100
            x-max-page-items: 500
          description: A pagination size for collection requests.
        - name: page_token
          in: query
          required: false
          schema:
            type: string
            maxLength: 255
          description: An opaque pagination token for collection requests.
      tags:
        - Flink Artifacts (artifact/v1)
      security:
        - cloud-api-key: []
        - confluent-sts-access-token: []
      responses:
        '200':
          description: Flink Artifact.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/artifact.v1.FlinkArtifactList'
          headers:
            X-Request-Id:
              schema:
                type: string
              description: The unique identifier for the API request.
            X-RateLimit-Limit:
              schema:
                type: integer
              description: The maximum number of requests you're permitted to make per time period.
            X-RateLimit-Remaining:
              schema:
                type: integer
              description: The number of requests remaining in the current rate limit window.
            X-RateLimit-Reset:
              schema:
                type: integer
              description: "The relative time in seconds until the current rate-limit window resets.  \n  \n**Important:**\
                \ This differs from Github and Twitter's same-named header which uses UTC epoch seconds. We use relative time\
                \ to avoid client/server time synchronization issues."
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/UnauthenticatedError'
        '403':
          $ref: '#/components/responses/UnauthorizedError'
        '429':
          $ref: '#/components/responses/RateLimitError'
        '500':
          $ref: '#/components/responses/DefaultSystemError'
    post:
      summary: Create a new Flink Artifact.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                cloud:
                  type: string
                  description: Cloud provider where the Flink Artifact archive is uploaded.
                  example: AWS
                  maxLength: 60
                  x-extensible-enum: [AWS, GCP, AZURE]
                region:
                  type: string
                  description: The Cloud provider region the Flink Artifact archive is uploaded.
                  example: us-east-1
                  maxLength: 60
                environment:
                  type: string
                  description: Environment the Flink Artifact belongs to.
                  example: env-00000
                  maxLength: 255
                display_name:
                  type: string
                  description: Unique name of the Flink Artifact per cloud, region, environment scope.
                  maxLength: 60
                class:
                  type: string
                  description: Java class or alias for the artifact as provided by developer. Deprecated
                  maxLength: 150
                  pattern: ^(([a-zA-Z][a-zA-Z_$0-9]*(\.[a-zA-Z][a-zA-Z_$0-9]*)*)\.)?([a-zA-Z][a-zA-Z_$0-9]*)$
                  example: io.confluent.example.SumScalarFunction
                  deprecated: true
                content_format:
                  type: string
                  description: Archive format of the Flink Artifact.
                  example: JAR
                  x-extensible-enum: [ZIP, JAR]
                description:
                  type: string
                  description: Description of the Flink Artifact.
                  maxLength: 256
                documentation_link:
                  type: string
                  description: Documentation link of the Flink Artifact.
                  maxLength: 512
                  pattern: ^$|^(http://|https://).+
                runtime_language:
                  type: string
                  description: Runtime language of the Flink Artifact.
                  example: JAVA
                  default: JAVA
                  x-extensible-enum: [JAVA, PYTHON]
                upload_source:
                  type: object
                  description: Upload source of the Flink Artifact source.
                  oneOf:
                    - $ref: '#/components/schemas/artifact.v1.UploadSource.PresignedUrl'
                  discriminator:
                    propertyName: location
                    mapping:
                      PRESIGNED_URL_LOCATION: '#/components/schemas/artifact.v1.UploadSource.PresignedUrl'
              required:
                - cloud
                - region
                - environment
                - display_name
                - upload_source
      x-lifecycle-stage: General Availability
      x-self-access: true
      operationId: createArtifactV1FlinkArtifact
      description: |-
        [![General Availability](https://img.shields.io/badge/Lifecycle%20Stage-General%20Availability-%2345c6e8)](#section/Versioning/API-Lifecycle-Policy)

        Make a request to create a flink artifact.
      parameters:
        - name: cloud
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/SearchFilter'
          example: AWS
          description: Scope the operation to the given cloud.
        - name: region
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/SearchFilter'
          example: us-east-1
          description: Scope the operation to the given region.
      tags:
        - Flink Artifacts (artifact/v1)
      security:
        - cloud-api-key: []
        - confluent-sts-access-token: []
      responses:
        '201':
          description: A Flink Artifact was created.
          headers:
            X-Request-Id:
              schema:
                type: string
              description: The unique identifier for the API request.
            X-RateLimit-Limit:
              schema:
                type: integer
              description: The maximum number of requests you're permitted to make per time period.
            X-RateLimit-Remaining:
              schema:
                type: integer
              description: The number of requests remaining in the current rate limit window.
            X-RateLimit-Reset:
              schema:
                type: integer
              description: "The relative time in seconds until the current rate-limit window resets.  \n  \n**Important:**\
                \ This differs from Github and Twitter's same-named header which uses UTC epoch seconds. We use relative time\
                \ to avoid client/server time synchronization issues."
            Location:
              schema:
                type: string
                format: uri
                example: https://api.confluent.cloud/artifact/v1/flink-artifacts/{id}
              description: FlinkArtifact resource uri
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/artifact.v1.FlinkArtifact'
                  - type: object
                    required:
                      - cloud
                      - region
                      - environment
                      - display_name
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/UnauthenticatedError'
        '403':
          $ref: '#/components/responses/UnauthorizedError'
        '409':
          $ref: '#/components/responses/ConflictError'
        '422':
          $ref: '#/components/responses/ValidationError'
        '429':
          $ref: '#/components/responses/RateLimitError'
        '500':
          $ref: '#/components/responses/DefaultSystemError'
  /artifact/v1/flink-artifacts/{id}:
    x-lifecycle-stage: General Availability
    x-self-access: true
    get:
      x-lifecycle-stage: General Availability
      x-self-access: true
      operationId: getArtifactV1FlinkArtifact
      summary: Read a Flink Artifact
      description: |-
        [![General Availability](https://img.shields.io/badge/Lifecycle%20Stage-General%20Availability-%2345c6e8)](#section/Versioning/API-Lifecycle-Policy)

        Make a request to read a flink artifact.
      parameters:
        - name: cloud
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/SearchFilter'
          example: AWS
          description: Scope the operation to the given cloud.
        - name: region
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/SearchFilter'
          example: us-east-1
          description: Scope the operation to the given region.
        - name: environment
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/SearchFilter'
          example: env-00000
          description: Scope the operation to the given environment.
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: The unique identifier for the flink artifact.
      tags:
        - Flink Artifacts (artifact/v1)
      security:
        - cloud-api-key: []
        - confluent-sts-access-token: []
      responses:
        '200':
          description: Flink Artifact.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/artifact.v1.FlinkArtifact'
                  - type: object
                    required:
                      - api_version
                      - kind
                      - id
                      - cloud
                      - region
                      - environment
                      - display_name
          headers:
            X-Request-Id:
              schema:
                type: string
              description: The unique identifier for the API request.
            X-RateLimit-Limit:
              schema:
                type: integer
              description: The maximum number of requests you're permitted to make per time period.
            X-RateLimit-Remaining:
              schema:
                type: integer
              description: The number of requests remaining in the current rate limit window.
            X-RateLimit-Reset:
              schema:
                type: integer
              description: "The relative time in seconds until the current rate-limit window resets.  \n  \n**Important:**\
                \ This differs from Github and Twitter's same-named header which uses UTC epoch seconds. We use relative time\
                \ to avoid client/server time synchronization issues."
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/UnauthenticatedError'
        '403':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '429':
          $ref: '#/components/responses/RateLimitError'
        '500':
          $ref: '#/components/responses/DefaultSystemError'
    patch:
      x-lifecycle-stage: General Availability
      x-self-access: true
      operationId: updateArtifactV1FlinkArtifact
      summary: Update a Flink Artifact
      description: |+
        [![General Availability](https://img.shields.io/badge/Lifecycle%20Stage-General%20Availability-%2345c6e8)](#section/Versioning/API-Lifecycle-Policy)

        Make a request to update a flink artifact.

      parameters:
        - name: cloud
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/SearchFilter'
          example: AWS
          description: Scope the operation to the given cloud.
        - name: region
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/SearchFilter'
          example: us-east-1
          description: Scope the operation to the given region.
        - name: environment
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/SearchFilter'
          example: env-00000
          description: Scope the operation to the given environment.
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: The unique identifier for the flink artifact.
      tags:
        - Flink Artifacts (artifact/v1)
      security:
        - cloud-api-key: []
        - confluent-sts-access-token: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/artifact.v1.FlinkArtifact'
      responses:
        '200':
          description: Flink Artifact.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/artifact.v1.FlinkArtifact'
                  - type: object
                    required:
                      - api_version
                      - kind
                      - id
                      - cloud
                      - region
                      - environment
                      - display_name
          headers:
            X-Request-Id:
              schema:
                type: string
              description: The unique identifier for the API request.
            X-RateLimit-Limit:
              schema:
                type: integer
              description: The maximum number of requests you're permitted to make per time period.
            X-RateLimit-Remaining:
              schema:
                type: integer
              description: The number of requests remaining in the current rate limit window.
            X-RateLimit-Reset:
              schema:
                type: integer
              description: "The relative time in seconds until the current rate-limit window resets.  \n  \n**Important:**\
                \ This differs from Github and Twitter's same-named header which uses UTC epoch seconds. We use relative time\
                \ to avoid client/server time synchronization issues."
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/UnauthenticatedError'
        '403':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '409':
          $ref: '#/components/responses/ConflictError'
        '422':
          $ref: '#/components/responses/ValidationError'
        '429':
          $ref: '#/components/responses/RateLimitError'
        '500':
          $ref: '#/components/responses/DefaultSystemError'
    delete:
      x-lifecycle-stage: General Availability
      x-self-access: true
      operationId: deleteArtifactV1FlinkArtifact
      summary: Delete a Flink Artifact
      description: |-
        [![General Availability](https://img.shields.io/badge/Lifecycle%20Stage-General%20Availability-%2345c6e8)](#section/Versioning/API-Lifecycle-Policy)

        Make a request to delete a flink artifact.
      parameters:
        - name: cloud
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/SearchFilter'
          example: AWS
          description: Scope the operation to the given cloud.
        - name: region
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/SearchFilter'
          example: us-east-1
          description: Scope the operation to the given region.
        - name: environment
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/SearchFilter'
          example: env-00000
          description: Scope the operation to the given environment.
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: The unique identifier for the flink artifact.
      tags:
        - Flink Artifacts (artifact/v1)
      security:
        - cloud-api-key: []
        - confluent-sts-access-token: []
      responses:
        '204':
          description: A Flink Artifact is being deleted.
          headers:
            X-Request-Id:
              schema:
                type: string
              description: The unique identifier for the API request.
            X-RateLimit-Limit:
              schema:
                type: integer
              description: The maximum number of requests you're permitted to make per time period.
            X-RateLimit-Remaining:
              schema:
                type: integer
              description: The number of requests remaining in the current rate limit window.
            X-RateLimit-Reset:
              schema:
                type: integer
              description: "The relative time in seconds until the current rate-limit window resets.  \n  \n**Important:**\
                \ This differs from Github and Twitter's same-named header which uses UTC epoch seconds. We use relative time\
                \ to avoid client/server time synchronization issues."
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/UnauthenticatedError'
        '403':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '429':
          $ref: '#/components/responses/RateLimitError'
        '500':
          $ref: '#/components/responses/DefaultSystemError'
  /artifact/v1/presigned-upload-url:
    x-lifecycle-stage: General Availability
    x-self-access: true
    post:
      summary: Request a presigned upload URL for a new Flink Artifact.
      description: |-
        [![General Availability](https://img.shields.io/badge/Lifecycle%20Stage-General%20Availability-%2345c6e8)](#section/Versioning/API-Lifecycle-Policy)

        Request a presigned upload URL to upload a Flink Artifact archive.
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/artifact.v1.PresignedUrlRequest'
                - type: object
                  required:
                    - content_format
                    - cloud
                    - region
                    - environment
      x-lifecycle-stage: General Availability
      x-self-access: true
      x-name: artifact.v1.PresignedUrl
      operationId: presigned-upload-urlArtifactV1PresignedUrl
      tags:
        - Presigned Urls (artifact/v1)
      security:
        - cloud-api-key: []
      responses:
        '200':
          description: Presigned Url.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/artifact.v1.PresignedUrl'
                  - type: object
                    required:
                      - api_version
                      - kind
          headers:
            X-Request-Id:
              schema:
                type: string
              description: The unique identifier for the API request.
            X-RateLimit-Limit:
              schema:
                type: integer
              description: The maximum number of requests you're permitted to make per time period.
            X-RateLimit-Remaining:
              schema:
                type: integer
              description: The number of requests remaining in the current rate limit window.
            X-RateLimit-Reset:
              schema:
                type: integer
              description: "The relative time in seconds until the current rate-limit window resets.  \n  \n**Important:**\
                \ This differs from Github and Twitter's same-named header which uses UTC epoch seconds. We use relative time\
                \ to avoid client/server time synchronization issues."
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/UnauthenticatedError'
        '403':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '429':
          $ref: '#/components/responses/RateLimitError'
        '500':
          $ref: '#/components/responses/DefaultSystemError'
components:
  schemas:
    artifact.v1.FlinkArtifact:
      type: object
      description: |-
        FlinkArtifact objects represent Flink Artifacts on Confluent Cloud.


        ## The Flink Artifacts Model
        <SchemaDefinition schemaRef="#/components/schemas/artifact.v1.FlinkArtifact" />
      properties:
        api_version:
          type: string
          enum:
            - artifact/v1
          description: APIVersion defines the schema version of this representation of a resource.
          readOnly: true
        kind:
          type: string
          description: Kind defines the object this REST resource represents.
          readOnly: true
          enum:
            - FlinkArtifact
        id:
          description: ID is the "natural identifier" for an object within its scope/namespace; it is normally unique across
            time but not space. That is, you can assume that the ID will not be reclaimed and reused after an object is deleted
            ("time"); however, it may collide with IDs for other object `kinds` or objects of the same `kind` within a different
            scope/namespace ("space").
          type: string
          maxLength: 255
          readOnly: true
          example: dlz-f3a90de
        metadata:
          allOf:
            - $ref: '#/components/schemas/ObjectMeta'
            - properties:
                self:
                  example: https://api.confluent.cloud/artifact/v1/flink-artifacts/fa-12345
                resource_name:
                  example: crn://confluent.cloud/organization=9bb441c4-edef-46ac-8a41-c49e44a3fd9a/flink-artifact=fa-12345
        cloud:
          type: string
          description: Cloud provider where the Flink Artifact archive is uploaded.
          example: AWS
          maxLength: 60
          x-extensible-enum: [AWS, GCP, AZURE]
        region:
          type: string
          description: The Cloud provider region the Flink Artifact archive is uploaded.
          example: us-east-1
          maxLength: 60
        environment:
          type: string
          description: Environment the Flink Artifact belongs to.
          example: env-00000
          maxLength: 255
        display_name:
          type: string
          description: Unique name of the Flink Artifact per cloud, region, environment scope.
          maxLength: 60
        class:
          type: string
          description: Java class or alias for the artifact as provided by developer. Deprecated
          maxLength: 150
          pattern: ^(([a-zA-Z][a-zA-Z_$0-9]*(\.[a-zA-Z][a-zA-Z_$0-9]*)*)\.)?([a-zA-Z][a-zA-Z_$0-9]*)$
          example: io.confluent.example.SumScalarFunction
          deprecated: true
          x-immutable: true
        content_format:
          type: string
          description: Archive format of the Flink Artifact.
          example: JAR
          x-extensible-enum: [ZIP, JAR]
        description:
          type: string
          description: Description of the Flink Artifact.
          maxLength: 256
        documentation_link:
          type: string
          description: Documentation link of the Flink Artifact.
          maxLength: 512
          pattern: ^$|^(http://|https://).+
        runtime_language:
          type: string
          description: Runtime language of the Flink Artifact.
          example: JAVA
          default: JAVA
          x-extensible-enum: [JAVA, PYTHON]
        versions:
          type: array
          description: Versions associated with this Flink Artifact.
          items:
            $ref: '#/components/schemas/artifact.v1.FlinkArtifactVersion'
    artifact.v1.PresignedUrl:
      type: object
      description: |-
        Request a presigned upload URL for new Flink Artifact. Note that
        the URL policy expires in one hour. If the policy expires, you can request
        a new presigned upload URL.


        ## The Presigned Urls Model
        <SchemaDefinition schemaRef="#/components/schemas/artifact.v1.PresignedUrl" />
      properties:
        api_version:
          type: string
          enum:
            - artifact/v1
          description: APIVersion defines the schema version of this representation of a resource.
          readOnly: true
        kind:
          type: string
          description: Kind defines the object this REST resource represents.
          readOnly: true
          enum:
            - PresignedUrl
        content_format:
          type: string
          description: Content format of the Flink Artifact archive.
          example: JAR
          x-extensible-enum: [ZIP, JAR]
          readOnly: true
        cloud:
          type: string
          description: Cloud provider where the Flink Artifact archive is uploaded.
          example: AWS
          x-extensible-enum: [AWS, GCP, AZURE]
          readOnly: true
        region:
          type: string
          description: The Cloud provider region the Flink Artifact archive is uploaded.
          example: us-east-1
          readOnly: true
        environment:
          type: string
          description: The Environment the uploaded Flink Artifact belongs to.
          example: env-00000
          readOnly: true
        upload_id:
          type: string
          description: Unique identifier of this upload.
          example: e53bb2e8-8de3-49fa-9fb1-4e3fd9a16b66
          readOnly: true
        upload_url:
          type: string
          format: uri
          description: Upload URL for the Flink Artifact archive.
          example: https://confluent-flink-artifacts-stag-us-west-2.s3.dualstack.us-west-2.amazonaws.com/
          readOnly: true
        upload_form_data:
          type: object
          description: Upload form data of the Flink Artifact. All values should be strings.
          example:
            bucket: confluent-flink-artifacts-stag-us-west-2
          # yamllint disable-line rule:line-length
            key: staging/flink-artifact/2f37f0b6-f8da-4e8b-bc5f-282ebb0511be/flink-e53bb2e8-8de3-49fa-9fb1-4e3fd9a16b66/artifact.jar
            policy: string
            x-amz-algorithm: AWS4-HMAC-SHA256
            x-amz-credential: string
            x-amz-date: 20230725T013857Z
            x-amz-security-token: string
            x-amz-signature: string
          readOnly: true
    artifact.v1.FlinkArtifactVersion:
      type: object
      description: |
        Version of the Flink Artifact
      properties:
        version:
          type: string
          description: Version id of the Flink Artifact.
          example: cfa-ver-001
          maxLength: 60
        release_notes:
          type: string
          description: Release Notes of the Flink Artifact version.
          maxLength: 256
        is_beta:
          type: boolean
          description: Flag to specify stability of the version
        artifact_id:
          type: object
          description: The Flink Artifact this version belongs to.
          allOf:
            - $ref: '#/components/schemas/artifact.v1.FlinkArtifact'
        upload_source:
          type: object
          oneOf:
            - $ref: '#/components/schemas/artifact.v1.UploadSource.PresignedUrl'
        # yamllint disable-line rule:line-length
          description: Upload source of the Flink Artifact Version.
          discriminator:
            propertyName: location
            mapping:
              PRESIGNED_URL_LOCATION: '#/components/schemas/artifact.v1.UploadSource.PresignedUrl'
      required:
        - version
        - artifact_id
        - upload_source
    artifact.v1.PresignedUrlRequest:
      type: object
      description: |
        Request schema of the presigned upload URL.
      properties:
        api_version:
          type: string
          enum:
            - artifact/v1
          description: APIVersion defines the schema version of this representation of a resource.
          readOnly: true
        kind:
          type: string
          description: Kind defines the object this REST resource represents.
          readOnly: true
          enum:
            - PresignedUrlRequest
        id:
          description: ID is the "natural identifier" for an object within its scope/namespace; it is normally unique across
            time but not space. That is, you can assume that the ID will not be reclaimed and reused after an object is deleted
            ("time"); however, it may collide with IDs for other object `kinds` or objects of the same `kind` within a different
            scope/namespace ("space").
          type: string
          maxLength: 255
          readOnly: true
          example: dlz-f3a90de
        metadata:
          allOf:
            - $ref: '#/components/schemas/ObjectMeta'
            - properties:
                self:
                  example: https://api.confluent.cloud/artifact/v1/presigned-url-requests/pur-12345
                resource_name:
                  example: crn://confluent.cloud/organization=9bb441c4-edef-46ac-8a41-c49e44a3fd9a/presigned-url-request=pur-12345
        content_format:
          type: string
          example: JAR
          description: Archive format of the Flink Artifact.
          x-extensible-enum: [JAR, ZIP]
        cloud:
          type: string
          example: AWS
          description: Cloud provider where the Flink Artifact archive is uploaded.
          x-extensible-enum: [AWS, GCP, AZURE]
        region:
          type: string
          example: us-east-1
          description: The Cloud provider region the Flink Artifact archive is uploaded.
          maxLength: 60
        environment:
          type: string
          example: env-00000
          description: The Environment the uploaded Flink Artifact belongs to.
          maxLength: 255
    artifact.v1.UploadSource.PresignedUrl:
      type: object
      description: |-
        Request a presigned upload URL for new Flink Artifact. Note that
        the URL policy expires in one hour. If the policy expires, you can request
        a new presigned upload URL.


        ## The Presigned Urls Model
        <SchemaDefinition schemaRef="#/components/schemas/artifact.v1.PresignedUrl" />
      properties:
        api_version:
          type: string
          enum:
            - artifact.v1/UploadSource
          description: APIVersion defines the schema version of this representation of a resource.
          readOnly: true
        kind:
          type: string
          description: Kind defines the object this REST resource represents.
          readOnly: true
          enum:
            - PresignedUrl
        id:
          description: ID is the "natural identifier" for an object within its scope/namespace; it is normally unique across
            time but not space. That is, you can assume that the ID will not be reclaimed and reused after an object is deleted
            ("time"); however, it may collide with IDs for other object `kinds` or objects of the same `kind` within a different
            scope/namespace ("space").
          type: string
          maxLength: 255
          readOnly: true
          example: dlz-f3a90de
        metadata:
          allOf:
            - $ref: '#/components/schemas/ObjectMeta'
            - properties:
                self:
                  example: https://api.confluent.cloud/artifact.v1/UploadSource/presigned-urls/pu-12345
                resource_name:
                  example: crn://confluent.cloud/organization=9bb441c4-edef-46ac-8a41-c49e44a3fd9a/presigned-url=pu-12345
        location:
          type: string
          description: |
            Location of the Flink Artifact source.
          x-extensible-enum: [PRESIGNED_URL_LOCATION]
          example: PRESIGNED_URL_LOCATION
        upload_id:
          type: string
          example: e53bb2e8-8de3-49fa-9fb1-4e3fd9a16b66
        # yamllint disable-line rule:line-length
          description: Upload ID returned by the `/presigned-upload-url` API. This field returns an empty string in all responses.
    SearchFilter:
      description: Filter a collection by a string search
      type: string
    artifact.v1.FlinkArtifactList:
      type: object
      description: |-
        FlinkArtifact objects represent Flink Artifacts on Confluent Cloud.


        ## The Flink Artifacts Model
        <SchemaDefinition schemaRef="#/components/schemas/artifact.v1.FlinkArtifact" />
      required:
        - api_version
        - kind
        - metadata
        - data
      properties:
        api_version:
          type: string
          enum:
            - artifact/v1
          description: APIVersion defines the schema version of this representation of a resource.
          readOnly: true
        kind:
          type: string
          description: Kind defines the object this REST resource represents.
          readOnly: true
          enum:
            - FlinkArtifactList
        metadata:
          allOf:
            - $ref: '#/components/schemas/ListMeta'
            - properties:
                first:
                  example: https://api.confluent.cloud/artifact/v1/flink-artifacts
                last:
                  example: https://api.confluent.cloud/artifact/v1/flink-artifacts?page_token=bcAOehAY8F16YD84Z1wT
                prev:
                  example: https://api.confluent.cloud/artifact/v1/flink-artifacts?page_token=YIXRY97wWYmwzrax4dld
                next:
                  example: https://api.confluent.cloud/artifact/v1/flink-artifacts?page_token=UvmDWOB1iwfAIBPj6EYb
        data:
          type: array
          description: A data property that contains an array of resource items. Each entry in the array is a separate resource.
          items:
            allOf:
              - $ref: '#/components/schemas/artifact.v1.FlinkArtifact'
              - type: object
                required:
                  - id
                  - metadata
                  - cloud
                  - region
                  - environment
                  - display_name
          uniqueItems: true
    ObjectMeta:
      description: ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create.
      required:
        - self
      properties:
        self:
          description: Self is a Uniform Resource Locator (URL) at which an object can be addressed. This URL encodes the
            service location, API version, and other particulars necessary to locate the resource at a point in time
          type: string
          format: uri
          readOnly: true
          example: https://api.confluent.cloud/v2/kafka-clusters/lkc-f3a90de
        resource_name:
          description: Resource Name is a Uniform Resource Identifier (URI) that is globally unique across space and time.
            It is represented as a Confluent Resource Name
          type: string
          format: uri
          readOnly: true
          example: crn://confluent.cloud/kafka=lkc-f3a90de
        created_at:
          type: string
          format: date-time
          example: '2006-01-02T15:04:05-07:00'
          readOnly: true
          description: The date and time at which this object was created. It is represented in RFC3339 format and is in UTC.
        updated_at:
          type: string
          format: date-time
          example: '2006-01-02T15:04:05-07:00'
          readOnly: true
          description: The date and time at which this object was last updated. It is represented in RFC3339 format and is
            in UTC.
        deleted_at:
          type: string
          format: date-time
          example: '2006-01-02T15:04:05-07:00'
          readOnly: true
          description: The date and time at which this object was (or will be) deleted. It is represented in RFC3339 format
            and is in UTC.
      readOnly: true
    ListMeta:
      type: object
      description: ListMeta describes metadata that resource collections may have
      properties:
        first:
          description: A link to the first page of results. If a response does not contain a first link, then direct navigation
            to the first page is not supported.
          type: string
          format: uri
          nullable: true
          example: https://api.confluent.cloud/v2/resourcekinds
        last:
          description: A link to the last page of results. If a response does not contain a last link, then direct navigation
            to the last page is not supported.
          type: string
          format: uri
          nullable: true
          example: https://api.confluent.cloud/v2/resourcekinds?page_token=bcAOehAY8F16YD84Z1wT
        prev:
          description: A link to the previous page of results. If a response does not contain a prev link, then either there
            is no previous data or backwards traversal through the result set is not supported.
          type: string
          format: uri
          nullable: true
          example: https://api.confluent.cloud/v2/resourcekinds?page_token=YIXRY97wWYmwzrax4dld
        next:
          description: A link to the next page of results. If a response does not contain a next link, then there is no more
            data available.
          type: string
          format: uri
          nullable: true
          example: https://api.confluent.cloud/v2/resourcekinds?page_token=UvmDWOB1iwfAIBPj6EYb
        total_size:
          description: Number of records in the full result set. This response may be paginated and have a smaller number
            of records.
          type: integer
          format: int32
          minimum: 0
          example: 123
    ObjectReference:
      type: object
      description: ObjectReference provides information for you to locate the referred object
      required:
        - id
        - related
        - resource_name
      properties:
        id:
          type: string
          description: ID of the referred resource
          minLength: 1
          maxLength: 255
        environment:
          type: string
          description: Environment of the referred resource, if env-scoped
          minLength: 1
          maxLength: 255
        related:
          type: string
          format: uri
          description: API URL for accessing or modifying the referred object
          minLength: 1
          readOnly: true
        resource_name:
          type: string
          format: uri
          description: CRN reference to the referred resource
          minLength: 1
          readOnly: true
        api_version:
          type: string
          description: API group and version of the referred resource
          minLength: 1
          readOnly: true
        kind:
          type: string
          description: Kind of the referred resource
          minLength: 1
          readOnly: true
    Failure:
      type: object
      description: Provides information about problems encountered while performing an operation.
      required:
        - errors
      properties:
        errors:
          description: List of errors which caused this operation to fail
          type: array
          items:
            $ref: '#/components/schemas/Error'
          uniqueItems: true
    Error:
      type: object
      description: Describes a particular error encountered while performing an operation.
      properties:
        id:
          description: A unique identifier for this particular occurrence of the problem.
          type: string
          maxLength: 255
        status:
          description: The HTTP status code applicable to this problem, expressed as a string value.
          type: string
        code:
          description: An application-specific error code, expressed as a string value.
          type: string
        title:
          description: A short, human-readable summary of the problem. It **SHOULD NOT** change from occurrence to occurrence
            of the problem, except for purposes of localization.
          type: string
        detail:
          description: A human-readable explanation specific to this occurrence of the problem.
          type: string
        source:
          type: object
          description: If this error was caused by a particular part of the API request, the source will point to the query
            string parameter or request body property that caused it.
          properties:
            pointer:
              description: A JSON Pointer [RFC6901] to the associated entity in the request document [e.g. "/spec" for a spec
                object, or "/spec/title" for a specific field].
              type: string
            parameter:
              description: A string indicating which query parameter caused the error.
              type: string
  securitySchemes:
    cloud-api-key:
      type: http
      scheme: basic
      description: Authenticate with Cloud API Keys using HTTP Basic Auth. Treat the Cloud API Key ID as the username and
        Cloud API Key Secret as the password.
    confluent-sts-access-token:
      type: oauth2
      description: Authenticate with Confluent API using this credentials (JSON Web Tokens) following OAuth 2.0.
      flows:
        clientCredentials:
          tokenUrl: https://api.confluent.cloud/sts/v1/oauth2/token
          scopes: {}
  responses:
    BadRequestError:
      description: Bad Request
      headers:
        X-Request-Id:
          schema:
            type: string
          description: The unique identifier for the API request.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Failure'
          example:
            errors:
              - id: ed42afdc-f0d5-4c0d-b428-9fc6ed6e279d
                status: '400'
                code: invalid_filter
                title: Invalid Filter
                detail: The 'delorean' resource can't be filtered by 'num_doors'
                source:
                  parameter: num_doors
    UnauthenticatedError:
      x-summary: Unauthorized
      description: The request lacks valid authentication credentials for this resource.
      headers:
        X-Request-Id:
          schema:
            type: string
          description: The unique identifier for the API request.
        WWW-Authenticate:
          schema:
            type: string
          description: The unique identifier for the API request.
          example: Basic error="invalid_key", error_description="The API Key is invalid"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Failure'
          example:
            errors:
              - id: ed42afdc-f0d5-4c0d-b428-9fc6ed6e279d
                status: '401'
                code: user_unauthenticated
                title: Authentication Required
                detail: Valid authentication credentials must be provided
    OverQuotaError:
      x-summary: Over Quota
      description: The request would exceed one or more quotas.
      headers:
        X-Request-Id:
          schema:
            type: string
          description: The unique identifier for the API request.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Failure'
          example:
            errors:
              - id: ed42afdc-f0d5-4c0d-b428-9fc6ed6e279d
                status: '402'
                code: quota_exceeded
                title: Kafka Clusters Per Org Quota Exceeded
                detail: 'The request would exceed the quota: kafka_clusters_per_environment'
    UnauthorizedError:
      x-summary: Forbidden
      description: The access credentials were considered insufficient to grant access
      headers:
        X-Request-Id:
          schema:
            type: string
          description: The unique identifier for the API request.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Failure'
          example:
            errors:
              - id: ed42afdc-f0d5-4c0d-b428-9fc6ed6e279d
                status: '403'
                code: user_unauthorized
                title: User Access Unauthorized
                detail: The user 'mcfly' is not allowed to access the 'delorean' resource without the 'plutonium' role.
    ConflictError:
      x-summary: Conflict
      description: The request is in conflict with the current server state
      headers:
        X-Request-Id:
          schema:
            type: string
          description: The unique identifier for the API request.
        Location:
          schema:
            type: string
            format: uri
            example: https://api.confluent.cloud/{object}/{id}
          description: Resource URI of conflicting resource
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Failure'
          example:
            errors:
              - id: ed42afdc-f0d5-4c0d-b428-9fc6ed6e279d
                status: '409'
                code: resource_already_exists
                title: Resource Already exists
                detail: The entitlement '91e3e86f-fca6-4f14-98f5-a48e64113ce2' already exists.
    NotFoundError:
      description: Not Found
      headers:
        X-Request-Id:
          schema:
            type: string
          description: The unique identifier for the API request.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Failure'
          example:
            errors:
              - id: ed42afdc-f0d5-4c0d-b428-9fc6ed6e279d
                status: '404'
                title: Not Found
    ValidationError:
      description: Validation Failed
      headers:
        X-Request-Id:
          schema:
            type: string
          description: The unique identifier for the API request.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Failure'
          example:
            errors:
              - status: '422'
                code: invalid_configuration
                id: ed42afdc-f0d5-4c0d-b428-9fc6ed6e279d
                title: Validation Failed
                detail: "The property '/cluster/storage_size' of type string did not match the following type: integer"
                source:
                  pointer: /cluster/storage_size
    RateLimitError:
      description: Rate Limit Exceeded
      headers:
        X-Request-Id:
          schema:
            type: string
          description: The unique identifier for the API request.
        X-RateLimit-Limit:
          schema:
            type: integer
          description: The maximum number of requests you're permitted to make per time period.
        X-RateLimit-Remaining:
          schema:
            type: integer
          description: The number of requests remaining in the current rate limit window.
        X-RateLimit-Reset:
          schema:
            type: integer
          description: "The relative time in seconds until the current rate-limit window resets.  \n  \n**Important:** This\
            \ differs from Github and Twitter's same-named header which uses UTC epoch seconds. We use relative time to avoid\
            \ client/server time synchronization issues."
        Retry-After:
          schema:
            type: integer
          description: The number of seconds to wait until the rate limit window resets. Only sent when the rate limit is
            reached.
    DefaultSystemError:
      description: Oops, something went wrong!
      headers:
        X-Request-Id:
          schema:
            type: string
          description: The unique identifier for the API request.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Failure'
          example:
            errors:
              - id: ed42afdc-f0d5-4c0d-b428-9fc6ed6e279d
                status: '500'
                code: out_of_gas
                title: DeLorean Out Of Gas
                detail: The DeLorean has run out of gas, but Doc Brown will fill 'er up for you asap
tags:
  - name: Flink Artifacts (artifact/v1)
    description: |-
      [![General Availability](https://img.shields.io/badge/Lifecycle%20Stage-General%20Availability-%2345c6e8)](#section/Versioning/API-Lifecycle-Policy)

      FlinkArtifact objects represent Flink Artifacts on Confluent Cloud.


      ## The Flink Artifacts Model
      <SchemaDefinition schemaRef="#/components/schemas/artifact.v1.FlinkArtifact" />
  - name: Presigned Urls (artifact/v1)
    description: |-
      [![General Availability](https://img.shields.io/badge/Lifecycle%20Stage-General%20Availability-%2345c6e8)](#section/Versioning/API-Lifecycle-Policy)

      Request a presigned upload URL for new Flink Artifact. Note that
      the URL policy expires in one hour. If the policy expires, you can request
      a new presigned upload URL.


      ## The Presigned Urls Model
      <SchemaDefinition schemaRef="#/components/schemas/artifact.v1.PresignedUrl" />
  - name: Flink Artifact Versions (artifact/v1)
    description: |-
      [![General Availability](https://img.shields.io/badge/Lifecycle%20Stage-General%20Availability-%2345c6e8)](#section/Versioning/API-Lifecycle-Policy)

      FlinkArtifactVersion objects represent Flink Artifact Versions on Confluent Cloud.


      ## The Flink Artifact Versions Model
      <SchemaDefinition schemaRef="#/components/schemas/artifact.v1.FlinkArtifactVersion" />
