# Code generated by generator.py. DO NOT EDIT.
# Source: scaffold/minispec.yaml
---
openapi: 3.0.0
info:
  title: Scaffolding API
  version: 0.0.1
servers:
  - url: https://api.confluent.cloud
    description: Confluent Cloud production
paths:
  /scaffold/v1/template-collections:
    x-lifecycle-stage: Early Access
    x-self-access: false
    x-request-access-name: Scaffolding API v1
    get:
      x-lifecycle-stage: Early Access
      x-self-access: false
      x-request-access-name: Scaffolding API v1
      operationId: listScaffoldV1TemplateCollections
      summary: List of Template Collections
      description: |-
        [![Early Access](https://img.shields.io/badge/Lifecycle%20Stage-Early%20Access-%2345c6e8)](#section/Versioning/API-Lifecycle-Policy) [![Request Access To Scaffolding API v1](https://img.shields.io/badge/-Request%20Access%20To%20Scaffolding%20API%20v1-%23bc8540)](mailto:ccloud-api-access+scaffold-v1-early-access@confluent.io?subject=Request%20to%20join%20scaffold/v1%20API%20Early%20Access&body=I%E2%80%99d%20like%20to%20join%20the%20Confluent%20Cloud%20API%20Early%20Access%20for%20scaffold/v1%20to%20provide%20early%20feedback%21%20My%20Cloud%20Organization%20ID%20is%20%3Cretrieve%20from%20https%3A//confluent.cloud/settings/billing/payment%3E.)

        Retrieve a sorted, filtered, paginated list of all template collections.
      parameters:
        - name: page_size
          in: query
          required: false
          schema:
            type: integer
            default: 10
            maximum: 100
            x-max-page-items: 500
          description: A pagination size for collection requests.
        - name: page_token
          in: query
          required: false
          schema:
            type: string
            maxLength: 255
          description: An opaque pagination token for collection requests.
      tags:
        - Template Collections (scaffold/v1)
      responses:
        '200':
          description: Template Collection.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/scaffold.v1.TemplateCollectionList'
          headers:
            X-Request-Id:
              schema:
                type: string
              description: The unique identifier for the API request.
            X-RateLimit-Limit:
              schema:
                type: integer
              description: The maximum number of requests you're permitted to make per time period.
            X-RateLimit-Remaining:
              schema:
                type: integer
              description: The number of requests remaining in the current rate limit window.
            X-RateLimit-Reset:
              schema:
                type: integer
              description: "The relative time in seconds until the current rate-limit window resets.  \n  \n**Important:**\
                \ This differs from Github and Twitter's same-named header which uses UTC epoch seconds. We use relative time\
                \ to avoid client/server time synchronization issues."
        '400':
          $ref: '#/components/responses/BadRequestError'
        '429':
          $ref: '#/components/responses/RateLimitError'
        '500':
          $ref: '#/components/responses/DefaultSystemError'
  /scaffold/v1/template-collections/{name}:
    x-lifecycle-stage: Early Access
    x-self-access: false
    x-request-access-name: Scaffolding API v1
    get:
      x-lifecycle-stage: Early Access
      x-self-access: false
      x-request-access-name: Scaffolding API v1
      operationId: getScaffoldV1TemplateCollection
      summary: Read a Template Collection
      description: |-
        [![Early Access](https://img.shields.io/badge/Lifecycle%20Stage-Early%20Access-%2345c6e8)](#section/Versioning/API-Lifecycle-Policy) [![Request Access To Scaffolding API v1](https://img.shields.io/badge/-Request%20Access%20To%20Scaffolding%20API%20v1-%23bc8540)](mailto:ccloud-api-access+scaffold-v1-early-access@confluent.io?subject=Request%20to%20join%20scaffold/v1%20API%20Early%20Access&body=I%E2%80%99d%20like%20to%20join%20the%20Confluent%20Cloud%20API%20Early%20Access%20for%20scaffold/v1%20to%20provide%20early%20feedback%21%20My%20Cloud%20Organization%20ID%20is%20%3Cretrieve%20from%20https%3A//confluent.cloud/settings/billing/payment%3E.)

        Make a request to read a template collection.
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
          description: The name of the template collection.
      tags:
        - Template Collections (scaffold/v1)
      responses:
        '200':
          description: Template Collection.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/scaffold.v1.TemplateCollection'
                  - type: object
                    required:
                      - api_version
                      - kind
                      - spec
                    properties:
                      spec:
                        type: object
                        required:
                          - name
          headers:
            X-Request-Id:
              schema:
                type: string
              description: The unique identifier for the API request.
            X-RateLimit-Limit:
              schema:
                type: integer
              description: The maximum number of requests you're permitted to make per time period.
            X-RateLimit-Remaining:
              schema:
                type: integer
              description: The number of requests remaining in the current rate limit window.
            X-RateLimit-Reset:
              schema:
                type: integer
              description: "The relative time in seconds until the current rate-limit window resets.  \n  \n**Important:**\
                \ This differs from Github and Twitter's same-named header which uses UTC epoch seconds. We use relative time\
                \ to avoid client/server time synchronization issues."
        '400':
          $ref: '#/components/responses/BadRequestError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '429':
          $ref: '#/components/responses/RateLimitError'
        '500':
          $ref: '#/components/responses/DefaultSystemError'
  /scaffold/v1/template-collections/{template-collection-name}/templates:
    x-lifecycle-stage: Early Access
    x-self-access: false
    x-request-access-name: Scaffolding API v1
    get:
      x-lifecycle-stage: Early Access
      x-self-access: false
      x-request-access-name: Scaffolding API v1
      operationId: listScaffoldV1Templates
      summary: List of Templates
      description: |-
        [![Early Access](https://img.shields.io/badge/Lifecycle%20Stage-Early%20Access-%2345c6e8)](#section/Versioning/API-Lifecycle-Policy) [![Request Access To Scaffolding API v1](https://img.shields.io/badge/-Request%20Access%20To%20Scaffolding%20API%20v1-%23bc8540)](mailto:ccloud-api-access+scaffold-v1-early-access@confluent.io?subject=Request%20to%20join%20scaffold/v1%20API%20Early%20Access&body=I%E2%80%99d%20like%20to%20join%20the%20Confluent%20Cloud%20API%20Early%20Access%20for%20scaffold/v1%20to%20provide%20early%20feedback%21%20My%20Cloud%20Organization%20ID%20is%20%3Cretrieve%20from%20https%3A//confluent.cloud/settings/billing/payment%3E.)

        Retrieve a sorted, filtered, paginated list of all templates.
      parameters:
        - name: page_size
          in: query
          required: false
          schema:
            type: integer
            default: 10
            maximum: 100
            x-max-page-items: 500
          description: A pagination size for collection requests.
        - name: page_token
          in: query
          required: false
          schema:
            type: string
            maxLength: 255
          description: An opaque pagination token for collection requests.
        - name: template-collection-name
          in: path
          required: true
          schema:
            type: string
          description: The Template Collection Name
      tags:
        - Templates (scaffold/v1)
      responses:
        '200':
          description: Template.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/scaffold.v1.TemplateList'
          headers:
            X-Request-Id:
              schema:
                type: string
              description: The unique identifier for the API request.
            X-RateLimit-Limit:
              schema:
                type: integer
              description: The maximum number of requests you're permitted to make per time period.
            X-RateLimit-Remaining:
              schema:
                type: integer
              description: The number of requests remaining in the current rate limit window.
            X-RateLimit-Reset:
              schema:
                type: integer
              description: "The relative time in seconds until the current rate-limit window resets.  \n  \n**Important:**\
                \ This differs from Github and Twitter's same-named header which uses UTC epoch seconds. We use relative time\
                \ to avoid client/server time synchronization issues."
        '400':
          $ref: '#/components/responses/BadRequestError'
        '429':
          $ref: '#/components/responses/RateLimitError'
        '500':
          $ref: '#/components/responses/DefaultSystemError'
  /scaffold/v1/template-collections/{template-collection-name}/templates/{name}:
    x-lifecycle-stage: Early Access
    x-self-access: false
    x-request-access-name: Scaffolding API v1
    get:
      x-lifecycle-stage: Early Access
      x-self-access: false
      x-request-access-name: Scaffolding API v1
      operationId: getScaffoldV1Template
      summary: Read a Template
      description: |-
        [![Early Access](https://img.shields.io/badge/Lifecycle%20Stage-Early%20Access-%2345c6e8)](#section/Versioning/API-Lifecycle-Policy) [![Request Access To Scaffolding API v1](https://img.shields.io/badge/-Request%20Access%20To%20Scaffolding%20API%20v1-%23bc8540)](mailto:ccloud-api-access+scaffold-v1-early-access@confluent.io?subject=Request%20to%20join%20scaffold/v1%20API%20Early%20Access&body=I%E2%80%99d%20like%20to%20join%20the%20Confluent%20Cloud%20API%20Early%20Access%20for%20scaffold/v1%20to%20provide%20early%20feedback%21%20My%20Cloud%20Organization%20ID%20is%20%3Cretrieve%20from%20https%3A//confluent.cloud/settings/billing/payment%3E.)

        Make a request to read a template.
      parameters:
        - name: template-collection-name
          in: path
          required: true
          schema:
            type: string
          description: The Template Collection Name
        - name: name
          in: path
          required: true
          schema:
            type: string
          description: The name of the template.
      tags:
        - Templates (scaffold/v1)
      responses:
        '200':
          description: Template.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/scaffold.v1.Template'
                  - type: object
                    required:
                      - api_version
                      - kind
                      - spec
                    properties:
                      spec:
                        type: object
                        required:
                          - name
                          - display_name
                          - description
                          - version
                          - language
                          - tags
                          - template_collection
          headers:
            X-Request-Id:
              schema:
                type: string
              description: The unique identifier for the API request.
            X-RateLimit-Limit:
              schema:
                type: integer
              description: The maximum number of requests you're permitted to make per time period.
            X-RateLimit-Remaining:
              schema:
                type: integer
              description: The number of requests remaining in the current rate limit window.
            X-RateLimit-Reset:
              schema:
                type: integer
              description: "The relative time in seconds until the current rate-limit window resets.  \n  \n**Important:**\
                \ This differs from Github and Twitter's same-named header which uses UTC epoch seconds. We use relative time\
                \ to avoid client/server time synchronization issues."
        '400':
          $ref: '#/components/responses/BadRequestError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '429':
          $ref: '#/components/responses/RateLimitError'
        '500':
          $ref: '#/components/responses/DefaultSystemError'
  /scaffold/v1/template-collections/{template-collection-name}/templates/{name}/apply:
    x-lifecycle-stage: Early Access
    x-self-access: false
    x-request-access-name: Scaffolding API v1
    post:
      description: |-
        [![Early Access](https://img.shields.io/badge/Lifecycle%20Stage-Early%20Access-%2345c6e8)](#section/Versioning/API-Lifecycle-Policy) [![Request Access To Scaffolding API v1](https://img.shields.io/badge/-Request%20Access%20To%20Scaffolding%20API%20v1-%23bc8540)](mailto:ccloud-api-access+scaffold-v1-early-access@confluent.io?subject=Request%20to%20join%20scaffold/v1%20API%20Early%20Access&body=I%E2%80%99d%20like%20to%20join%20the%20Confluent%20Cloud%20API%20Early%20Access%20for%20scaffold/v1%20to%20provide%20early%20feedback%21%20My%20Cloud%20Organization%20ID%20is%20%3Cretrieve%20from%20https%3A//confluent.cloud/settings/billing/payment%3E.)

        Generates an application project from a template using provided option values.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              description: Request payload for the endpoint that applies a template.
              required:
                - options
              properties:
                options:
                  type: object
                  description: Values for the options of the template.
                  additionalProperties:
                    type: string
      x-lifecycle-stage: Early Access
      x-self-access: false
      x-request-access-name: Scaffolding API v1
      x-name: scaffold.v1.Template
      operationId: applyScaffoldV1Template
      summary: Apply a Template
      parameters:
        - name: template-collection-name
          in: path
          required: true
          schema:
            type: string
          description: The Template Collection Name
        - name: name
          in: path
          required: true
          schema:
            type: string
          description: The name of the template.
      tags:
        - Templates (scaffold/v1)
      responses:
        '200':
          description: OK
          content:
            application/zip:
              schema:
                type: string
                format: binary
        '400':
          $ref: '#/components/responses/BadRequestError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '429':
          $ref: '#/components/responses/RateLimitError'
        '500':
          $ref: '#/components/responses/DefaultSystemError'
components:
  schemas:
    scaffold.v1.TemplateCollection:
      type: object
      description: |-
        Template collections curate sets of templates.

        ## The Template Collections Model
        <SchemaDefinition schemaRef="#/components/schemas/scaffold.v1.TemplateCollection" />
      properties:
        api_version:
          type: string
          enum:
            - scaffold/v1
          description: APIVersion defines the schema version of this representation of a resource.
          readOnly: true
        kind:
          type: string
          description: Kind defines the object this REST resource represents.
          readOnly: true
          enum:
            - TemplateCollection
        metadata:
          allOf:
            - $ref: '#/components/schemas/ObjectMeta'
            - properties:
                self:
                  example: https://api.confluent.cloud/scaffold/v1/template-collections/12345
                resource_name:
                  example: crn://confluent.cloud/organization=9bb441c4-edef-46ac-8a41-c49e44a3fd9a/template-collection=12345
        spec:
          $ref: '#/components/schemas/scaffold.v1.TemplateCollectionSpec'
    scaffold.v1.Template:
      type: object
      description: |-
        Templates can be used to generate application projects.

        ## The Templates Model
        <SchemaDefinition schemaRef="#/components/schemas/scaffold.v1.Template" />
      properties:
        api_version:
          type: string
          enum:
            - scaffold/v1
          description: APIVersion defines the schema version of this representation of a resource.
          readOnly: true
        kind:
          type: string
          description: Kind defines the object this REST resource represents.
          readOnly: true
          enum:
            - Template
        metadata:
          allOf:
            - $ref: '#/components/schemas/ObjectMeta'
            - properties:
                self:
                  example: https://api.confluent.cloud/scaffold/v1/templates/12345
                resource_name:
                  example: crn://confluent.cloud/notification-template=12345
        spec:
          $ref: '#/components/schemas/scaffold.v1.TemplateSpec'
    scaffold.v1.TemplateOption:
      description: An option of a template.
      type: object
      required:
        - display_name
        - description
      properties:
        display_name:
          type: string
          description: >-
            A few words that accurately and concisely represent the human readable
            form of the option's key.
          maxLength: 60
        description:
          type: string
          description: 1-2 sentences that describe the option.
        hint:
          type: string
          description: >-
            An optional description or example of the information required for a form
            field, typically rendered within the entry field of a form.
        format:
          type: string
          description: >-
            An optional format modifer that serves as a hint for UI presentation. If
            specified, the only allowed value at this time is `password` to hint the UI
            to mask the input.
          x-extensible-enum:
            - PASSWORD
        pattern:
          type: string
          description: >-
            An optional regular expression pattern such that only values matched by this
            pattern will be accepted.
          format: regex
        enum:
          type: array
          description: An optional attribute that specifies possible values for this option.
          items:
            type: string
        initial_value:
          type: string
          description: Initial value of the form field for this option.
        min_length:
          type: integer
          format: int32
          description: The minimum number of characters that must be provided for an option.
          default: 0
          minimum: 0
        examples:
          type: array
          description: Examples of valid values for this option.
          items:
            type: string
    scaffold.v1.TemplateCollectionList:
      type: object
      description: |-
        Template collections curate sets of templates.

        ## The Template Collections Model
        <SchemaDefinition schemaRef="#/components/schemas/scaffold.v1.TemplateCollection" />
      required:
        - api_version
        - kind
        - metadata
        - data
      properties:
        api_version:
          type: string
          enum:
            - scaffold/v1
          description: APIVersion defines the schema version of this representation of a resource.
          readOnly: true
        kind:
          type: string
          description: Kind defines the object this REST resource represents.
          readOnly: true
          enum:
            - TemplateCollectionList
        metadata:
          allOf:
            - $ref: '#/components/schemas/ListMeta'
            - properties:
                first:
                  example: https://api.confluent.cloud/scaffold/v1/template-collections
                last:
                  example: https://api.confluent.cloud/scaffold/v1/template-collections?page_token=bcAOehAY8F16YD84Z1wT
                prev:
                  example: https://api.confluent.cloud/scaffold/v1/template-collections?page_token=YIXRY97wWYmwzrax4dld
                next:
                  example: https://api.confluent.cloud/scaffold/v1/template-collections?page_token=UvmDWOB1iwfAIBPj6EYb
        data:
          type: array
          description: A data property that contains an array of resource items. Each entry in the array is a separate resource.
          items:
            allOf:
              - $ref: '#/components/schemas/scaffold.v1.TemplateCollection'
              - type: object
                required:
                  - metadata
                  - spec
                properties:
                  spec:
                    type: object
                    required:
                      - name
          uniqueItems: true
    scaffold.v1.TemplateCollectionSpec:
      type: object
      description: The desired state of the Template Collection
      properties:
        name:
          type: string
          pattern: ^[a-z0-9]+[a-z0-9-]{0,251}[a-z0-9]+$
          minLength: 2
          maxLength: 253
          example: confluent-cloud
          description: The name of the template collection.
        display_name:
          type: string
          maxLength: 60
          example: Confluent Cloud
          description: The display name of the template collection.
        description:
          type: string
          maxLength: 300
          example: The template collection used by the Confluent Cloud UI.
          description: The description of the template collection.
      x-enable-id: false
      x-enable-listmeta: true
      x-enable-objectmeta: true
    scaffold.v1.TemplateList:
      type: object
      description: |-
        Templates can be used to generate application projects.

        ## The Templates Model
        <SchemaDefinition schemaRef="#/components/schemas/scaffold.v1.Template" />
      required:
        - api_version
        - kind
        - metadata
        - data
      properties:
        api_version:
          type: string
          enum:
            - scaffold/v1
          description: APIVersion defines the schema version of this representation of a resource.
          readOnly: true
        kind:
          type: string
          description: Kind defines the object this REST resource represents.
          readOnly: true
          enum:
            - TemplateList
        metadata:
          allOf:
            - $ref: '#/components/schemas/ListMeta'
            - properties:
                first:
                  example: https://api.confluent.cloud/scaffold/v1/templates
                last:
                  example: https://api.confluent.cloud/scaffold/v1/templates?page_token=bcAOehAY8F16YD84Z1wT
                prev:
                  example: https://api.confluent.cloud/scaffold/v1/templates?page_token=YIXRY97wWYmwzrax4dld
                next:
                  example: https://api.confluent.cloud/scaffold/v1/templates?page_token=UvmDWOB1iwfAIBPj6EYb
        data:
          type: array
          description: A data property that contains an array of resource items. Each entry in the array is a separate resource.
          items:
            allOf:
              - $ref: '#/components/schemas/scaffold.v1.Template'
              - type: object
                required:
                  - metadata
                  - spec
                properties:
                  spec:
                    type: object
                    required:
                      - name
                      - display_name
                      - description
                      - version
                      - language
                      - tags
                      - template_collection
          uniqueItems: true
    scaffold.v1.TemplateSpec:
      type: object
      description: The desired state of the Template
      properties:
        name:
          type: string
          pattern: ^[a-z0-9]+[a-z0-9-]{0,251}[a-z0-9]+$
          minLength: 2
          maxLength: 253
          example: python-consumer
          description: The name of the template.
        display_name:
          type: string
          maxLength: 60
          example: Python Consumer
          description: The display name of the template.
        description:
          type: string
          maxLength: 300
          example: >-
            A Python application project that reads messages from a topic in
            Confluent Cloud. Ideal for developers new to Kafka who want to
            explore data or create business dashboards.
          description: The description of the template.
        version:
          type: string
        # https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string
          pattern: >-
            ^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-]
            [0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]
            +(?:\.[0-9a-zA-Z-]+)*))?$
          example: 0.5.0
          description: >-
            The semantic version of the template, of the form <major>.<minor>.<patch>.
            Bump the version with each non-trivial change.
        language:
          type: string
          example: Python
          description: The primary programming language that projects generated from the template will use.
          x-extensible-enum:
            - Clojure
            - C/C++
            - C#
            - Java
            - JavaScript
            - Go
            - Groovy
            - Kotlin
            - Python
            - Ruby
            - Rust
            - Scala
            - SQL
            - .NET
        tags:
          type: array
          items:
            type: string
            x-extensible-enum:
              - analytics
              - apache flink
              - connector
              - consumer
              - filter
              - getting started
              - gradle
              - kafka connect
              - kafka streams
              - maven
              - producer
              - sink
              - source
          example:
            - kafka streams
            - filter
            - analytics
          description: >-
            Tags are keywords or very short phrases (1-3 words) that apply to the template
            and that help with search and organization. Use lowercase characters and numbers
            in each word, and separate words with a space.
        options:
          type: object
          description: Options of the template.
          additionalProperties:
            $ref: '#/components/schemas/scaffold.v1.TemplateOption'
        template_collection:
          allOf:
            - $ref: '#/components/schemas/GlobalObjectReference'
          description: The template_collection to which this belongs.
      x-enable-id: false
      x-enable-listmeta: true
      x-enable-objectmeta: true
    ObjectMeta:
      description: ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create.
      required:
        - self
      properties:
        self:
          description: Self is a Uniform Resource Locator (URL) at which an object can be addressed. This URL encodes the
            service location, API version, and other particulars necessary to locate the resource at a point in time
          type: string
          format: uri
          readOnly: true
          example: https://api.confluent.cloud/v2/kafka-clusters/lkc-f3a90de
        resource_name:
          description: Resource Name is a Uniform Resource Identifier (URI) that is globally unique across space and time.
            It is represented as a Confluent Resource Name
          type: string
          format: uri
          readOnly: true
          example: crn://confluent.cloud/kafka=lkc-f3a90de
        created_at:
          type: string
          format: date-time
          example: '2006-01-02T15:04:05-07:00'
          readOnly: true
          description: The date and time at which this object was created. It is represented in RFC3339 format and is in UTC.
        updated_at:
          type: string
          format: date-time
          example: '2006-01-02T15:04:05-07:00'
          readOnly: true
          description: The date and time at which this object was last updated. It is represented in RFC3339 format and is
            in UTC.
        deleted_at:
          type: string
          format: date-time
          example: '2006-01-02T15:04:05-07:00'
          readOnly: true
          description: The date and time at which this object was (or will be) deleted. It is represented in RFC3339 format
            and is in UTC.
      readOnly: true
    ListMeta:
      type: object
      description: ListMeta describes metadata that resource collections may have
      properties:
        first:
          description: A link to the first page of results. If a response does not contain a first link, then direct navigation
            to the first page is not supported.
          type: string
          format: uri
          nullable: true
          example: https://api.confluent.cloud/v2/resourcekinds
        last:
          description: A link to the last page of results. If a response does not contain a last link, then direct navigation
            to the last page is not supported.
          type: string
          format: uri
          nullable: true
          example: https://api.confluent.cloud/v2/resourcekinds?page_token=bcAOehAY8F16YD84Z1wT
        prev:
          description: A link to the previous page of results. If a response does not contain a prev link, then either there
            is no previous data or backwards traversal through the result set is not supported.
          type: string
          format: uri
          nullable: true
          example: https://api.confluent.cloud/v2/resourcekinds?page_token=YIXRY97wWYmwzrax4dld
        next:
          description: A link to the next page of results. If a response does not contain a next link, then there is no more
            data available.
          type: string
          format: uri
          nullable: true
          example: https://api.confluent.cloud/v2/resourcekinds?page_token=UvmDWOB1iwfAIBPj6EYb
        total_size:
          description: Number of records in the full result set. This response may be paginated and have a smaller number
            of records.
          type: integer
          format: int32
          minimum: 0
          example: 123
    ObjectReference:
      type: object
      description: ObjectReference provides information for you to locate the referred object
      required:
        - id
        - related
        - resource_name
      properties:
        id:
          type: string
          description: ID of the referred resource
          minLength: 1
          maxLength: 255
        environment:
          type: string
          description: Environment of the referred resource, if env-scoped
          minLength: 1
          maxLength: 255
        related:
          type: string
          format: uri
          description: API URL for accessing or modifying the referred object
          minLength: 1
          readOnly: true
        resource_name:
          type: string
          format: uri
          description: CRN reference to the referred resource
          minLength: 1
          readOnly: true
        api_version:
          type: string
          description: API group and version of the referred resource
          minLength: 1
          readOnly: true
        kind:
          type: string
          description: Kind of the referred resource
          minLength: 1
          readOnly: true
    GlobalObjectReference:
      type: object
      description: ObjectReference provides information for you to locate the referred object
      required:
        - id
        - related
        - resource_name
      properties:
        id:
          type: string
          description: ID of the referred resource
          minLength: 1
          maxLength: 255
        related:
          type: string
          format: uri
          description: API URL for accessing or modifying the referred object
          minLength: 1
          readOnly: true
        resource_name:
          type: string
          format: uri
          description: CRN reference to the referred resource
          minLength: 1
          readOnly: true
    Failure:
      type: object
      description: Provides information about problems encountered while performing an operation.
      required:
        - errors
      properties:
        errors:
          description: List of errors which caused this operation to fail
          type: array
          items:
            $ref: '#/components/schemas/Error'
          uniqueItems: true
    Error:
      type: object
      description: Describes a particular error encountered while performing an operation.
      properties:
        id:
          description: A unique identifier for this particular occurrence of the problem.
          type: string
          maxLength: 255
        status:
          description: The HTTP status code applicable to this problem, expressed as a string value.
          type: string
        code:
          description: An application-specific error code, expressed as a string value.
          type: string
        title:
          description: A short, human-readable summary of the problem. It **SHOULD NOT** change from occurrence to occurrence
            of the problem, except for purposes of localization.
          type: string
        detail:
          description: A human-readable explanation specific to this occurrence of the problem.
          type: string
        source:
          type: object
          description: If this error was caused by a particular part of the API request, the source will point to the query
            string parameter or request body property that caused it.
          properties:
            pointer:
              description: A JSON Pointer [RFC6901] to the associated entity in the request document [e.g. "/spec" for a spec
                object, or "/spec/title" for a specific field].
              type: string
            parameter:
              description: A string indicating which query parameter caused the error.
              type: string
  securitySchemes: {}
  responses:
    BadRequestError:
      description: Bad Request
      headers:
        X-Request-Id:
          schema:
            type: string
          description: The unique identifier for the API request.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Failure'
          example:
            errors:
              - id: ed42afdc-f0d5-4c0d-b428-9fc6ed6e279d
                status: '400'
                code: invalid_filter
                title: Invalid Filter
                detail: The 'delorean' resource can't be filtered by 'num_doors'
                source:
                  parameter: num_doors
    UnauthenticatedError:
      x-summary: Unauthorized
      description: The request lacks valid authentication credentials for this resource.
      headers:
        X-Request-Id:
          schema:
            type: string
          description: The unique identifier for the API request.
        WWW-Authenticate:
          schema:
            type: string
          description: The unique identifier for the API request.
          example: Basic error="invalid_key", error_description="The API Key is invalid"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Failure'
          example:
            errors:
              - id: ed42afdc-f0d5-4c0d-b428-9fc6ed6e279d
                status: '401'
                code: user_unauthenticated
                title: Authentication Required
                detail: Valid authentication credentials must be provided
    OverQuotaError:
      x-summary: Over Quota
      description: The request would exceed one or more quotas.
      headers:
        X-Request-Id:
          schema:
            type: string
          description: The unique identifier for the API request.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Failure'
          example:
            errors:
              - id: ed42afdc-f0d5-4c0d-b428-9fc6ed6e279d
                status: '402'
                code: quota_exceeded
                title: Kafka Clusters Per Org Quota Exceeded
                detail: 'The request would exceed the quota: kafka_clusters_per_environment'
    UnauthorizedError:
      x-summary: Forbidden
      description: The access credentials were considered insufficient to grant access
      headers:
        X-Request-Id:
          schema:
            type: string
          description: The unique identifier for the API request.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Failure'
          example:
            errors:
              - id: ed42afdc-f0d5-4c0d-b428-9fc6ed6e279d
                status: '403'
                code: user_unauthorized
                title: User Access Unauthorized
                detail: The user 'mcfly' is not allowed to access the 'delorean' resource without the 'plutonium' role.
    ConflictError:
      x-summary: Conflict
      description: The request is in conflict with the current server state
      headers:
        X-Request-Id:
          schema:
            type: string
          description: The unique identifier for the API request.
        Location:
          schema:
            type: string
            format: uri
            example: https://api.confluent.cloud/{object}/{id}
          description: Resource URI of conflicting resource
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Failure'
          example:
            errors:
              - id: ed42afdc-f0d5-4c0d-b428-9fc6ed6e279d
                status: '409'
                code: resource_already_exists
                title: Resource Already exists
                detail: The entitlement '91e3e86f-fca6-4f14-98f5-a48e64113ce2' already exists.
    NotFoundError:
      description: Not Found
      headers:
        X-Request-Id:
          schema:
            type: string
          description: The unique identifier for the API request.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Failure'
          example:
            errors:
              - id: ed42afdc-f0d5-4c0d-b428-9fc6ed6e279d
                status: '404'
                title: Not Found
    ValidationError:
      description: Validation Failed
      headers:
        X-Request-Id:
          schema:
            type: string
          description: The unique identifier for the API request.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Failure'
          example:
            errors:
              - status: '422'
                code: invalid_configuration
                id: ed42afdc-f0d5-4c0d-b428-9fc6ed6e279d
                title: Validation Failed
                detail: "The property '/cluster/storage_size' of type string did not match the following type: integer"
                source:
                  pointer: /cluster/storage_size
    RateLimitError:
      description: Rate Limit Exceeded
      headers:
        X-Request-Id:
          schema:
            type: string
          description: The unique identifier for the API request.
        X-RateLimit-Limit:
          schema:
            type: integer
          description: The maximum number of requests you're permitted to make per time period.
        X-RateLimit-Remaining:
          schema:
            type: integer
          description: The number of requests remaining in the current rate limit window.
        X-RateLimit-Reset:
          schema:
            type: integer
          description: "The relative time in seconds until the current rate-limit window resets.  \n  \n**Important:** This\
            \ differs from Github and Twitter's same-named header which uses UTC epoch seconds. We use relative time to avoid\
            \ client/server time synchronization issues."
        Retry-After:
          schema:
            type: integer
          description: The number of seconds to wait until the rate limit window resets. Only sent when the rate limit is
            reached.
    DefaultSystemError:
      description: Oops, something went wrong!
      headers:
        X-Request-Id:
          schema:
            type: string
          description: The unique identifier for the API request.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Failure'
          example:
            errors:
              - id: ed42afdc-f0d5-4c0d-b428-9fc6ed6e279d
                status: '500'
                code: out_of_gas
                title: DeLorean Out Of Gas
                detail: The DeLorean has run out of gas, but Doc Brown will fill 'er up for you asap
tags:
  - name: Template Collections (scaffold/v1)
    description: |-
      [![Early Access](https://img.shields.io/badge/Lifecycle%20Stage-Early%20Access-%2345c6e8)](#section/Versioning/API-Lifecycle-Policy) [![Request Access To Scaffolding API v1](https://img.shields.io/badge/-Request%20Access%20To%20Scaffolding%20API%20v1-%23bc8540)](mailto:ccloud-api-access+scaffold-v1-early-access@confluent.io?subject=Request%20to%20join%20scaffold/v1%20API%20Early%20Access&body=I%E2%80%99d%20like%20to%20join%20the%20Confluent%20Cloud%20API%20Early%20Access%20for%20scaffold/v1%20to%20provide%20early%20feedback%21%20My%20Cloud%20Organization%20ID%20is%20%3Cretrieve%20from%20https%3A//confluent.cloud/settings/billing/payment%3E.)

      Template collections curate sets of templates.

      ## The Template Collections Model
      <SchemaDefinition schemaRef="#/components/schemas/scaffold.v1.TemplateCollection" />
  - name: Templates (scaffold/v1)
    description: |-
      [![Early Access](https://img.shields.io/badge/Lifecycle%20Stage-Early%20Access-%2345c6e8)](#section/Versioning/API-Lifecycle-Policy) [![Request Access To Scaffolding API v1](https://img.shields.io/badge/-Request%20Access%20To%20Scaffolding%20API%20v1-%23bc8540)](mailto:ccloud-api-access+scaffold-v1-early-access@confluent.io?subject=Request%20to%20join%20scaffold/v1%20API%20Early%20Access&body=I%E2%80%99d%20like%20to%20join%20the%20Confluent%20Cloud%20API%20Early%20Access%20for%20scaffold/v1%20to%20provide%20early%20feedback%21%20My%20Cloud%20Organization%20ID%20is%20%3Cretrieve%20from%20https%3A//confluent.cloud/settings/billing/payment%3E.)

      Templates can be used to generate application projects.

      ## The Templates Model
      <SchemaDefinition schemaRef="#/components/schemas/scaffold.v1.Template" />
